// 0, 7, 17, 1
#define BUILD_NUM 1
#define BUILD_NUM_STR  "1"

#define COREVERSION_NUM 0, 7, 17,
#define COREVERSION_NUM_STR  "0, 7, 17 "

#define FILE_VERSION	COREVERSION_NUM BUILD_NUM
#define PRODUCT_VERSION	COREVERSION_NUM BUILD_NUM

#ifdef UNICODE
#ifndef _DEBUG
#define FILE_VERSION_STR	COREVERSION_NUM_STR " UNICODE build " BUILD_NUM_STR
	#define PRODUCT_VERSION_STR	COREVERSION_NUM_STR " UNICODE build " BUILD_NUM_STR 
#else
#define FILE_VERSION_STR	COREVERSION_NUM_STR " DEBUG UNICODE build " BUILD_NUM_STR
#define PRODUCT_VERSION_STR	COREVERSION_NUM_STR " DEBUG UNICODE build " BUILD_NUM_STR
#endif
#else
#ifndef _DEBUG
	#define FILE_VERSION_STR	"0, 4, 3, build " BUILD_NUM_STR
	#define PRODUCT_VERSION_STR	"0, 4, 3, build " BUILD_NUM_STR
#else
	#define FILE_VERSION_STR	"0, 4, 3, DEBUG build " BUILD_NUM_STR
	#define PRODUCT_VERSION_STR	"0, 4, 3, DEBUG build " BUILD_NUM_STR
#endif
#endif
