// ---------------------------------------------------------------------------80
//                ICQ plugin for Miranda Instant Messenger
//                ________________________________________
//
// Copyright © 2001-2004 Richard Hughes, Martin Öberg
// Copyright © 2004-2008 Joe Kucera, Bio
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// -----------------------------------------------------------------------------
//
// File name      : $URL$
// Revision       : $Revision$
// Last change on : $Date$
// Last change by : $Author$
//
// DESCRIPTION:
//
//  ChangeInfo Plugin stuff
//
// -----------------------------------------------------------------------------

#include "icqoscar.h"

static ListTypeDataItem countries[]={
  {0   ,LPGEN("Unspecified")},
  {9999,LPGEN("Other")},
  {93  ,LPGEN("Afghanistan")},
  {355 ,LPGEN("Albania")},
  {213 ,LPGEN("Algeria")},
  {684 ,LPGEN("American Samoa")},
  {376 ,LPGEN("Andorra")},
  {244 ,LPGEN("Angola")},
  {101 ,LPGEN("Anguilla")},
  {102 ,LPGEN("Antigua and Barbuda")},
  {5902,LPGEN("Antilles")},
  {54  ,LPGEN("Argentina")},
  {374 ,LPGEN("Armenia")},
  {297 ,LPGEN("Aruba")},
  {247 ,LPGEN("Ascension Island")},
  {61  ,LPGEN("Australia")},
  {43  ,LPGEN("Austria")},
  {994 ,LPGEN("Azerbaijan")},
  {103 ,LPGEN("Bahamas")},
  {973 ,LPGEN("Bahrain")},
  {880 ,LPGEN("Bangladesh")},
  {104 ,LPGEN("Barbados")},
  {120 ,LPGEN("Barbuda")},
  {375 ,LPGEN("Belarus")},
  {32  ,LPGEN("Belgium")},
  {501 ,LPGEN("Belize")},
  {229 ,LPGEN("Benin")},
  {105 ,LPGEN("Bermuda")},
  {975 ,LPGEN("Bhutan")},
  {591 ,LPGEN("Bolivia")},
  {387 ,LPGEN("Bosnia and Herzegovina")},
  {267 ,LPGEN("Botswana")},
  {55  ,LPGEN("Brazil")},
  {106 ,LPGEN("British Virgin Islands")},
  {673 ,LPGEN("Brunei")},
  {359 ,LPGEN("Bulgaria")},
  {226 ,LPGEN("Burkina Faso")},
  {257 ,LPGEN("Burundi")},
  {855 ,LPGEN("Cambodia")},
  {237 ,LPGEN("Cameroon")},
  {107 ,LPGEN("Canada")},
  {178 ,LPGEN("Canary Islands")},
  {238 ,LPGEN("Cape Verde Islands")},
  {108 ,LPGEN("Cayman Islands")},
  {236 ,LPGEN("Central African Republic")},
  {235 ,LPGEN("Chad")},
  {56  ,LPGEN("Chile, Republic of")},
  {86  ,LPGEN("China")},
  {672 ,LPGEN("Christmas Island")},
  {6101,LPGEN("Cocos-Keeling Islands")},
  {6102,LPGEN("Cocos (Keeling) Islands")},
  {57  ,LPGEN("Colombia")},
  {2691,LPGEN("Comoros")},
  {243 ,LPGEN("Congo, Democratic Republic of (Zaire)")},
  {242 ,LPGEN("Congo, Republic of the")},
  {682 ,LPGEN("Cook Islands")},
  {506 ,LPGEN("Costa Rica")},
  {225 ,LPGEN("Cote d'Ivoire (Ivory Coast)")},
  {385 ,LPGEN("Croatia")},
  {53  ,LPGEN("Cuba")},
  {357 ,LPGEN("Cyprus")},
  {420 ,LPGEN("Czech Republic")},
  {45  ,LPGEN("Denmark")},
  {246 ,LPGEN("Diego Garcia")},
  {253 ,LPGEN("Djibouti")},
  {109 ,LPGEN("Dominica")},
  {110 ,LPGEN("Dominican Republic")},
  {593 ,LPGEN("Ecuador")},
  {20  ,LPGEN("Egypt")},
  {503 ,LPGEN("El Salvador")},
  {240 ,LPGEN("Equatorial Guinea")},
  {291 ,LPGEN("Eritrea")},
  {372 ,LPGEN("Estonia")},
  {251 ,LPGEN("Ethiopia")},
  {298 ,LPGEN("Faeroe Islands")},
  {500 ,LPGEN("Falkland Islands")},
  {679 ,LPGEN("Fiji")},
  {358 ,LPGEN("Finland")},
  {33  ,LPGEN("France")},
  {5901,LPGEN("French Antilles")},
  {594 ,LPGEN("French Guiana")},
  {689 ,LPGEN("French Polynesia")},
  {241 ,LPGEN("Gabon")},
  {220 ,LPGEN("Gambia")},
  {995 ,LPGEN("Georgia")},
  {49  ,LPGEN("Germany")},
  {233 ,LPGEN("Ghana")},
  {350 ,LPGEN("Gibraltar")},
  {30  ,LPGEN("Greece")},
  {299 ,LPGEN("Greenland")},
  {111 ,LPGEN("Grenada")},
  {590 ,LPGEN("Guadeloupe")},
  {671 ,LPGEN("Guam, US Territory of")},
  {502 ,LPGEN("Guatemala")},
  {224 ,LPGEN("Guinea")},
  {245 ,LPGEN("Guinea-Bissau")},
  {592 ,LPGEN("Guyana")},
  {509 ,LPGEN("Haiti")},
  {504 ,LPGEN("Honduras")},
  {852 ,LPGEN("Hong Kong")},
  {36  ,LPGEN("Hungary")},
  {354 ,LPGEN("Iceland")},
  {91  ,LPGEN("India")},
  {62  ,LPGEN("Indonesia")},
  {98  ,LPGEN("Iran (Islamic Republic of)")},
  {964 ,LPGEN("Iraq")},
  {353 ,LPGEN("Ireland")},
  {972 ,LPGEN("Israel")},
  {39  ,LPGEN("Italy")},
  {112 ,LPGEN("Jamaica")},
  {81  ,LPGEN("Japan")},
  {962 ,LPGEN("Jordan")},
  {705 ,LPGEN("Kazakhstan")},
  {254 ,LPGEN("Kenya")},
  {686 ,LPGEN("Kiribati")},
  {850 ,LPGEN("Korea, North")},
  {82  ,LPGEN("Korea, South")},
  {965 ,LPGEN("Kuwait")},
  {706 ,LPGEN("Kyrgyzstan")},
  {856 ,LPGEN("Laos")},
  {371 ,LPGEN("Latvia")},
  {961 ,LPGEN("Lebanon")},
  {266 ,LPGEN("Lesotho")},
  {231 ,LPGEN("Liberia")},
  {218 ,LPGEN("Libyan Arab Jamahiriya")},
  {4101,LPGEN("Liechtenstein")},
  {370 ,LPGEN("Lithuania")},
  {352 ,LPGEN("Luxembourg")},
  {853 ,LPGEN("Macau")},
  {389 ,LPGEN("Macedonia (F.Y.R.O.M.)")},
  {261 ,LPGEN("Madagascar")},
  {265 ,LPGEN("Malawi")},
  {60  ,LPGEN("Malaysia")},
  {960 ,LPGEN("Maldives")},
  {223 ,LPGEN("Mali")},
  {356 ,LPGEN("Malta")},
  {692 ,LPGEN("Marshall Islands")},
  {596 ,LPGEN("Martinique")},
  {222 ,LPGEN("Mauritania")},
  {230 ,LPGEN("Mauritius")},
  {269 ,LPGEN("Mayotte Island")},
  {52  ,LPGEN("Mexico")},
  {691 ,LPGEN("Micronesia, Federated States of")},
  {373 ,LPGEN("Moldova, Republic of")},
  {377 ,LPGEN("Monaco")},
  {976 ,LPGEN("Mongolia")},
  {113 ,LPGEN("Montserrat")},
  {212 ,LPGEN("Morocco")},
  {258 ,LPGEN("Mozambique")},
  {95  ,LPGEN("Myanmar")},
  {264 ,LPGEN("Namibia")},
  {674 ,LPGEN("Nauru")},
  {977 ,LPGEN("Nepal")},
  {31  ,LPGEN("Netherlands")},
  {599 ,LPGEN("Netherlands Antilles")},
  {114 ,LPGEN("Nevis")},
  {687 ,LPGEN("New Caledonia")},
  {64  ,LPGEN("New Zealand")},
  {505 ,LPGEN("Nicaragua")},
  {227 ,LPGEN("Niger")},
  {234 ,LPGEN("Nigeria")},
  {683 ,LPGEN("Niue")},
  {6722,LPGEN("Norfolk Island")},
  {47  ,LPGEN("Norway")},
  {968 ,LPGEN("Oman")},
  {92  ,LPGEN("Pakistan")},
  {680 ,LPGEN("Palau")},
  {507 ,LPGEN("Panama")},
  {675 ,LPGEN("Papua New Guinea")},
  {595 ,LPGEN("Paraguay")},
  {51  ,LPGEN("Peru")},
  {63  ,LPGEN("Philippines")},
  {48  ,LPGEN("Poland")},
  {351 ,LPGEN("Portugal")},
  {121 ,LPGEN("Puerto Rico")},
  {974 ,LPGEN("Qatar")},
  {262 ,LPGEN("Reunion Island")},
  {40  ,LPGEN("Romania")},
  {6701,LPGEN("Rota Island")},
  {7   ,LPGEN("Russia")},
  {250 ,LPGEN("Rwanda")},
  {290 ,LPGEN("Saint Helena")},
  {115 ,LPGEN("Saint Kitts")},
  {1141,LPGEN("Saint Kitts and Nevis")},
  {122 ,LPGEN("Saint Lucia")},
  {508 ,LPGEN("Saint Pierre and Miquelon")},
  {116 ,LPGEN("Saint Vincent and the Grenadines")},
  {670 ,LPGEN("Saipan Island")},
  {378 ,LPGEN("San Marino")},
  {239 ,LPGEN("Sao Tome and Principe")},
  {966 ,LPGEN("Saudi Arabia")},
  {442 ,LPGEN("Scotland")},
  {221 ,LPGEN("Senegal")},
  {248 ,LPGEN("Seychelles")},
  {232 ,LPGEN("Sierra Leone")},
  {65  ,LPGEN("Singapore")},
  {421 ,LPGEN("Slovakia")},
  {386 ,LPGEN("Slovenia")},
  {677 ,LPGEN("Solomon Islands")},
  {252 ,LPGEN("Somalia")},
  {27  ,LPGEN("South Africa")},
  {34  ,LPGEN("Spain")},
  {94  ,LPGEN("Sri Lanka")},
  {249 ,LPGEN("Sudan")},
  {597 ,LPGEN("Suriname")},
  {268 ,LPGEN("Swaziland")},
  {46  ,LPGEN("Sweden")},
  {41  ,LPGEN("Switzerland")},
  {963 ,LPGEN("Syrian Arab Republic")},
  {886 ,LPGEN("Taiwan")},
  {708 ,LPGEN("Tajikistan")},
  {255 ,LPGEN("Tanzania")},
  {66  ,LPGEN("Thailand")},
  {6702,LPGEN("Tinian Island")},
  {228 ,LPGEN("Togo")},
  {690 ,LPGEN("Tokelau")},
  {676 ,LPGEN("Tonga")},
  {117 ,LPGEN("Trinidad and Tobago")},
  {216 ,LPGEN("Tunisia")},
  {90  ,LPGEN("Turkey")},
  {709 ,LPGEN("Turkmenistan")},
  {118 ,LPGEN("Turks and Caicos Islands")},
  {688 ,LPGEN("Tuvalu")},
  {256 ,LPGEN("Uganda")},
  {380 ,LPGEN("Ukraine")},
  {971 ,LPGEN("United Arab Emirates")},
  {44  ,LPGEN("United Kingdom")},
  {598 ,LPGEN("Uruguay")},
  {1   ,LPGEN("USA")},
  {711 ,LPGEN("Uzbekistan")},
  {678 ,LPGEN("Vanuatu")},
  {379 ,LPGEN("Vatican City")},
  {58  ,LPGEN("Venezuela")},
  {84  ,LPGEN("Vietnam")},
  {123 ,LPGEN("Virgin Islands (USA)")},
  {441 ,LPGEN("Wales")},
  {681 ,LPGEN("Wallis and Futuna Islands")},
  {685 ,LPGEN("Western Samoa")},
  {967 ,LPGEN("Yemen")},
  {381 ,LPGEN("Yugoslavia")},
  {3811,LPGEN("Yugoslavia - Serbia")},
  {382 ,LPGEN("Yugoslavia - Montenegro")},
  {260 ,LPGEN("Zambia")},
  {263 ,LPGEN("Zimbabwe")},
};

static ListTypeDataItem timezones[]={
  {-100,LPGEN("Unspecified")},
  {24  ,LPGEN("GMT-12:00 Eniwetok; Kwajalein")},
  {23  ,LPGEN("GMT-11:30")},
  {22  ,LPGEN("GMT-11:00 Midway Island; Samoa")},
  {21  ,LPGEN("GMT-10:30")},
  {20  ,LPGEN("GMT-10:00 Hawaii")},
  {19  ,LPGEN("GMT-9:30")},
  {18  ,LPGEN("GMT-9:00 Alaska")},
  {17  ,LPGEN("GMT-8:30")},
  {16  ,LPGEN("GMT-8:00 Pacific Time; Tijuana")},
  {15  ,LPGEN("GMT-7:30")},
  {14  ,LPGEN("GMT-7:00 Arizona; Mountain Time")},
  {13  ,LPGEN("GMT-6:30")},
  {12  ,LPGEN("GMT-6:00 Central Time; Central America; Saskatchewan")},
  {11  ,LPGEN("GMT-5:30")},
  {10  ,LPGEN("GMT-5:00 Eastern Time; Bogota; Lima; Quito")},
  {9   ,LPGEN("GMT-4:30")},
  {8   ,LPGEN("GMT-4:00 Atlantic Time; Santiago; Caracas; La Paz")},
  {7   ,LPGEN("GMT-3:30 Newfoundland")},
  {6   ,LPGEN("GMT-3:00 Greenland; Buenos Aires; Georgetown")},
  {5   ,LPGEN("GMT-2:30")},
  {4   ,LPGEN("GMT-2:00 Mid-Atlantic")},
  {3   ,LPGEN("GMT-1:30")},
  {2   ,LPGEN("GMT-1:00 Cape Verde Islands; Azores")},
  {1   ,LPGEN("GMT-0:30")},
  {0   ,LPGEN("GMT+0:00 London; Dublin; Edinburgh; Lisbon; Casablanca")},
  {-1  ,LPGEN("GMT+0:30")},
  {-2  ,LPGEN("GMT+1:00 Central European Time; West Central Africa; Warsaw")},
  {-3  ,LPGEN("GMT+1:30")},
  {-4  ,LPGEN("GMT+2:00 Jerusalem; Helsinki; Harare; Cairo; Bucharest; Athens")},
  {-5  ,LPGEN("GMT+2:30")},
  {-6  ,LPGEN("GMT+3:00 Moscow; St. Petersburg; Nairobi; Kuwait; Baghdad")},
  {-7  ,LPGEN("GMT+3:30 Tehran")},
  {-8  ,LPGEN("GMT+4:00 Baku; Tbilisi; Yerevan; Abu Dhabi; Muscat")},
  {-9  ,LPGEN("GMT+4:30 Kabul")},
  {-10 ,LPGEN("GMT+5:00 Calcutta; Chennai; Mumbai; New Delhi; Ekaterinburg")},
  {-11 ,LPGEN("GMT+5:30")},
  {-12 ,LPGEN("GMT+6:00 Astana; Dhaka; Almaty; Novosibirsk; Sri Jayawardenepura")},
  {-13 ,LPGEN("GMT+6:30 Rangoon")},
  {-14 ,LPGEN("GMT+7:00 Bankok; Hanoi; Jakarta; Krasnoyarsk")},
  {-15 ,LPGEN("GMT+7:30")},
  {-16 ,LPGEN("GMT+8:00 Perth; Taipei; Singapore; Hong Kong; Beijing")},
  {-17 ,LPGEN("GMT+8:30")},
  {-18 ,LPGEN("GMT+9:00 Tokyo; Osaka; Seoul; Sapporo; Yakutsk")},
  {-19 ,LPGEN("GMT+9:30 Darwin; Adelaide")},
  {-20 ,LPGEN("GMT+10:00 East Australia; Guam; Vladivostok")},
  {-21 ,LPGEN("GMT+10:30")},
  {-22 ,LPGEN("GMT+11:00 Magadan; Solomon Is.; New Caledonia")},
  {-23 ,LPGEN("GMT+11:30")},
  {-24 ,LPGEN("GMT+12:00 Auckland; Wellington; Fiji; Kamchatka; Marshall Is.")},
};

static ListTypeDataItem occupations[] = {
  {0, LPGEN("Unspecified")},
  {1, LPGEN("Academic")},
  {2, LPGEN("Administrative")},
  {3, LPGEN("Art/Entertainment")},
  {4, LPGEN("College Student")},
  {5, LPGEN("Computers")},
  {6, LPGEN("Community & Social")},
  {7, LPGEN("Education")},
  {8, LPGEN("Engineering")},
  {9, LPGEN("Financial Services")},
  {10, LPGEN("Government")},
  {11, LPGEN("High School Student")},
  {12, LPGEN("Home")},
  {13, LPGEN("ICQ - Providing Help")},
  {14, LPGEN("Law")},
  {15, LPGEN("Managerial")},
  {16, LPGEN("Manufacturing")},
  {17, LPGEN("Medical/Health")},
  {18, LPGEN("Military")},
  {19, LPGEN("Non-Government Organization")},
  {20, LPGEN("Professional")},
  {21, LPGEN("Retail")},
  {22, LPGEN("Retired")},
  {23, LPGEN("Science & Research")},
  {24, LPGEN("Sports")},
  {25, LPGEN("Technical")},
  {26, LPGEN("University Student")},
  {27, LPGEN("Web Building")},
  {99, LPGEN("Other Services")}
};

static ListTypeDataItem genders[]={
  {0,LPGEN("Unspecified")},
  {'M',LPGEN("Male")},
  {'F',LPGEN("Female")},
};

static ListTypeDataItem months[]={
  {0, LPGEN("Unspecified")},
  {1, LPGEN("January")},
  {2, LPGEN("February")},
  {3, LPGEN("March")},
  {4, LPGEN("April")},
  {5, LPGEN("May")},
  {6, LPGEN("June")},
  {7, LPGEN("July")},
  {8, LPGEN("August")},
  {9, LPGEN("September")},
  {10,LPGEN("October")},
  {11,LPGEN("November")},
  {12,LPGEN("December")},
};

static ListTypeDataItem languages[]={
  {0, LPGEN("None")},
  {55,LPGEN("Afrikaans")},
  {58,LPGEN("Albanian")},
  {1, LPGEN("Arabic")},
  {59,LPGEN("Armenian")},
  {68,LPGEN("Azerbaijani")},
  {72,LPGEN("Belorussian")},
  {2, LPGEN("Bhojpuri")},
  {56,LPGEN("Bosnian")},
  {3, LPGEN("Bulgarian")},
  {4, LPGEN("Burmese")},
  {5, LPGEN("Cantonese")},
  {6, LPGEN("Catalan")},
  {61,LPGEN("Chamorro")},
  {7, LPGEN("Chinese")},
  {8, LPGEN("Croatian")},
  {9, LPGEN("Czech")},
  {10,LPGEN("Danish")},
  {11,LPGEN("Dutch")},
  {12,LPGEN("English")},
  {13,LPGEN("Esperanto")},
  {14,LPGEN("Estonian")},
  {15,LPGEN("Farci")},
  {16,LPGEN("Finnish")},
  {17,LPGEN("French")},
  {18,LPGEN("Gaelic")},
  {19,LPGEN("German")},
  {20,LPGEN("Greek")},
  {70,LPGEN("Gujarati")},
  {21,LPGEN("Hebrew")},
  {22,LPGEN("Hindi")},
  {23,LPGEN("Hungarian")},
  {24,LPGEN("Icelandic")},
  {25,LPGEN("Indonesian")},
  {26,LPGEN("Italian")},
  {27,LPGEN("Japanese")},
  {28,LPGEN("Khmer")},
  {29,LPGEN("Korean")},
  {69,LPGEN("Kurdish")},
  {30,LPGEN("Lao")},
  {31,LPGEN("Latvian")},
  {32,LPGEN("Lithuanian")},
  {65,LPGEN("Macedonian")},
  {33,LPGEN("Malay")},
  {63,LPGEN("Mandarin")},
  {62,LPGEN("Mongolian")},
  {34,LPGEN("Norwegian")},
  {57,LPGEN("Persian")},
  {35,LPGEN("Polish")},
  {36,LPGEN("Portuguese")},
  {60,LPGEN("Punjabi")},
  {37,LPGEN("Romanian")},
  {38,LPGEN("Russian")},
  {39,LPGEN("Serbo-Croatian")},
  {66,LPGEN("Sindhi")},
  {40,LPGEN("Slovak")},
  {41,LPGEN("Slovenian")},
  {42,LPGEN("Somali")},
  {43,LPGEN("Spanish")},
  {44,LPGEN("Swahili")},
  {45,LPGEN("Swedish")},
  {46,LPGEN("Tagalog")},
  {64,LPGEN("Taiwaness")},
  {71,LPGEN("Tamil")},
  {47,LPGEN("Tatar")},
  {48,LPGEN("Thai")},
  {49,LPGEN("Turkish")},
  {50,LPGEN("Ukrainian")},
  {51,LPGEN("Urdu")},
  {52,LPGEN("Vietnamese")},
  {67,LPGEN("Welsh")},
  {53,LPGEN("Yiddish")},
  {54,LPGEN("Yoruba")},
};

static ListTypeDataItem interests[]={
  {0, LPGEN("Unspecified")},
  {100, LPGEN("Art")},
  {101, LPGEN("Cars")},
  {102, LPGEN("Celebrity Fans")},
  {103, LPGEN("Collections")},
  {104, LPGEN("Computers")},
  {105, LPGEN("Culture & Literature")},
  {106, LPGEN("Fitness")},
  {107, LPGEN("Games")},
  {108, LPGEN("Hobbies")},
  {109, LPGEN("ICQ - Providing Help")},
  {110, LPGEN("Internet")},
  {111, LPGEN("Lifestyle")},
  {112, LPGEN("Movies/TV")},
  {113, LPGEN("Music")},
  {114, LPGEN("Outdoor Activities")},
  {115, LPGEN("Parenting")},
  {116, LPGEN("Pets/Animals")},
  {117, LPGEN("Religion")},
  {118, LPGEN("Science/Technology")},
  {119, LPGEN("Skills")},
  {120, LPGEN("Sports")},
  {121, LPGEN("Web Design")},
  {122, LPGEN("Nature and Environment")},
  {123, LPGEN("News & Media")},
  {124, LPGEN("Government")},
  {125, LPGEN("Business & Economy")},
  {126, LPGEN("Mystics")},
  {127, LPGEN("Travel")},
  {128, LPGEN("Astronomy")},
  {129, LPGEN("Space")},
  {130, LPGEN("Clothing")},
  {131, LPGEN("Parties")},
  {132, LPGEN("Women")},
  {133, LPGEN("Social science")},
  {134, LPGEN("60's")},
  {135, LPGEN("70's")},
  {136, LPGEN("80's")},
  {137, LPGEN("50's")},
  {138, LPGEN("Finance and corporate")},
  {139, LPGEN("Entertainment")},
  {140, LPGEN("Consumer electronics")},
  {141, LPGEN("Retail stores")},
  {142, LPGEN("Health and beauty")},
  {143, LPGEN("Media")},
  {144, LPGEN("Household products")},
  {145, LPGEN("Mail order catalog")},
  {146, LPGEN("Business services")},
  {147, LPGEN("Audio and visual")},
  {148, LPGEN("Sporting and athletic")},
  {149, LPGEN("Publishing")},
  {150, LPGEN("Home automation")}
};

static ListTypeDataItem pastbackground[]={
  {0,   LPGEN("Unspecified")},
  {300, LPGEN("Elementary School")},
  {301, LPGEN("High School")},
  {302, LPGEN("College")},
  {303, LPGEN("University")},
  {304, LPGEN("Military")},
  {305, LPGEN("Past Work Place")},
  {306, LPGEN("Past Organization")},
  {399, LPGEN("Other")}
};

static ListTypeDataItem affiliation[]={
  {0,   LPGEN("Unspecified")},
  {200, LPGEN("Alumni Org.")},
  {201, LPGEN("Charity Org.")},
  {202, LPGEN("Club/Social Org.")},
  {203, LPGEN("Community Org.")},
  {204, LPGEN("Cultural Org.")},
  {205, LPGEN("Fan Clubs")},
  {206, LPGEN("Fraternity/Sorority")},
  {207, LPGEN("Hobbyists Org.")},
  {208, LPGEN("International Org.")},
  {209, LPGEN("Nature and Environment Org.")},
  {210, LPGEN("Professional Org.")},
  {211, LPGEN("Scientific/Technical Org.")},
  {212, LPGEN("Self Improvement Group")},
  {213, LPGEN("Spiritual/Religious Org.")},
  {214, LPGEN("Sports Org.")},
  {215, LPGEN("Support Org.")},
  {216, LPGEN("Trade and Business Org.")},
  {217, LPGEN("Union")},
  {218, LPGEN("Volunteer Org.")},
  {299, LPGEN("Other")},
};

static ListTypeDataItem maritalstatuses[]={
  {0,  LPGEN("Unspecified")},
  {10, LPGEN("Single")},
  {11, LPGEN("Close relationships")},
  {12, LPGEN("Engaged")},
  {20, LPGEN("Married")},
  {30, LPGEN("Divorced")},
  {31, LPGEN("Separated")},
  {40, LPGEN("Widowed")}
};


const int ageRange[]={13,0x7FFF};  // 14, 130
const int yearRange[]={1753,0x7FFF}; // 1880, 2000
const int dayRange[]={1,31};


SettingItem setting[]={
  //personal
  {LPGEN("Personal"),       LI_DIVIDER},
  {LPGEN("Nickname"),       LI_STRING,     DBVT_ASCIIZ, "Nick"},
  {LPGEN("First name"),     LI_STRING,     DBVT_ASCIIZ, "FirstName"},
  {LPGEN("Last name"),      LI_STRING,     DBVT_ASCIIZ, "LastName"},
  {LPGEN("Age"),            LI_NUMBER,     DBVT_WORD,   "Age",        (void*)ageRange},
  {LPGEN("Gender"),         LI_LIST,       DBVT_BYTE,   "Gender",     genders, sizeof(genders)/sizeof(genders[0])},
  {LPGEN("About"),          LI_LONGSTRING, DBVT_ASCIIZ, "About"},
  //password
  {LPGEN("Password"),       LI_DIVIDER},
  {LPGEN("Password"),       LI_STRING|LIF_PASSWORD,DBVT_ASCIIZ, "Password"},
  //contact
  {LPGEN("Contact"),        LI_DIVIDER},
  {LPGEN("Primary e-mail"), LI_STRING,     DBVT_ASCIIZ, "e-mail"},
  {LPGEN("Secondary e-mail"), LI_STRING,   DBVT_ASCIIZ, "e-mail0"},
  {LPGEN("Tertiary e-mail"), LI_STRING,    DBVT_ASCIIZ, "e-mail1"},
  {LPGEN("Homepage"),       LI_STRING,     DBVT_ASCIIZ, "Homepage"},
  {LPGEN("Street"),         LI_STRING,     DBVT_ASCIIZ, "Street"},
  {LPGEN("City"),           LI_STRING,     DBVT_ASCIIZ, "City"},
  {LPGEN("State"),          LI_STRING,     DBVT_ASCIIZ, "State"},
  {LPGEN("ZIP/postcode"),   LI_STRING,     DBVT_ASCIIZ, "ZIP"},
  {LPGEN("Country"),        LI_LIST,       DBVT_WORD,   "Country",    countries, sizeof(countries)/sizeof(countries[0])},
  {LPGEN("Phone number"),   LI_STRING,     DBVT_ASCIIZ, "Phone"},
  {LPGEN("Fax number"),     LI_STRING,     DBVT_ASCIIZ, "Fax"},
  {LPGEN("Cellular number"),LI_STRING,     DBVT_ASCIIZ, "Cellular"},
  //more
  {LPGEN("Personal Detail"),LI_DIVIDER},
  {LPGEN("Timezone"),       LI_LIST|LIF_ZEROISVALID|LIF_SIGNED,DBVT_BYTE,   "Timezone", timezones, sizeof(timezones)/sizeof(timezones[0])},
  {LPGEN("Year of birth"),  LI_NUMBER,     DBVT_WORD,   "BirthYear",  (void*)yearRange},
  {LPGEN("Month of birth"), LI_LIST,       DBVT_BYTE,   "BirthMonth", months, sizeof(months)/sizeof(months[0])},
  {LPGEN("Day of birth"),   LI_NUMBER,     DBVT_BYTE,   "BirthDay",   (void*)dayRange},
  {LPGEN("Marital Status"), LI_LIST,       DBVT_BYTE,   "MaritalStatus", maritalstatuses, sizeof(maritalstatuses)/sizeof(maritalstatuses[0])},
  {LPGEN("Spoken language 1"), LI_LIST,    DBVT_ASCIIZ, "Language1",  languages, sizeof(languages)/sizeof(languages[0])},
  {LPGEN("Spoken language 2"), LI_LIST,    DBVT_ASCIIZ, "Language2",  languages, sizeof(languages)/sizeof(languages[0])},
  {LPGEN("Spoken language 3"), LI_LIST,    DBVT_ASCIIZ, "Language3",  languages, sizeof(languages)/sizeof(languages[0])},
  //more
  {LPGEN("Originally from"),LI_DIVIDER},
  {LPGEN("City"),           LI_STRING,     DBVT_ASCIIZ, "OriginCity"},
  {LPGEN("State"),          LI_STRING,     DBVT_ASCIIZ, "OriginState"},
  {LPGEN("Country"),        LI_LIST,       DBVT_WORD,   "OriginCountry",    countries, sizeof(countries)/sizeof(countries[0])},
  //work
  {LPGEN("Work"),           LI_DIVIDER},
  {LPGEN("Company name"),   LI_STRING,     DBVT_ASCIIZ, "Company"},
  {LPGEN("Company homepage"),LI_STRING,    DBVT_ASCIIZ, "CompanyHomepage"},
  {LPGEN("Company street"), LI_STRING,     DBVT_ASCIIZ, "CompanyStreet"},
  {LPGEN("Company city"),   LI_STRING,     DBVT_ASCIIZ, "CompanyCity"},
  {LPGEN("Company state"),  LI_STRING,     DBVT_ASCIIZ, "CompanyState"},
  {LPGEN("Company phone"),  LI_STRING,     DBVT_ASCIIZ, "CompanyPhone"},
  {LPGEN("Company fax"),    LI_STRING,     DBVT_ASCIIZ, "CompanyFax"},
  {LPGEN("Company ZIP/postcode"),LI_STRING,DBVT_ASCIIZ, "CompanyZIP"},
  {LPGEN("Company country"),LI_LIST,       DBVT_WORD,   "CompanyCountry",countries, sizeof(countries)/sizeof(countries[0])},
  {LPGEN("Company department"),LI_STRING,  DBVT_ASCIIZ, "CompanyDepartment"},
  {LPGEN("Company position"),LI_STRING,    DBVT_ASCIIZ, "CompanyPosition"},
  {LPGEN("Company occupation"),LI_LIST,    DBVT_WORD,   "CompanyOccupation", occupations, sizeof(occupations)/sizeof(occupations[0])},
  //interests
  {LPGEN("Personal Interests"),            LI_DIVIDER},
  {LPGEN("Interest category 1"),LI_LIST,   DBVT_ASCIIZ, "Interest0Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGEN("Interest areas 1"),LI_STRING,    DBVT_ASCIIZ, "Interest0Text"},
  {LPGEN("Interest category 2"),LI_LIST,   DBVT_ASCIIZ, "Interest1Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGEN("Interest areas 2"),LI_STRING,    DBVT_ASCIIZ, "Interest1Text"},
  {LPGEN("Interest category 3"),LI_LIST,   DBVT_ASCIIZ, "Interest2Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGEN("Interest areas 3"),LI_STRING,    DBVT_ASCIIZ, "Interest2Text"},
  {LPGEN("Interest category 4"),LI_LIST,   DBVT_ASCIIZ, "Interest3Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGEN("Interest areas 4"),LI_STRING,    DBVT_ASCIIZ, "Interest3Text"},
  //pastbackground
  {LPGEN("Past Background"),               LI_DIVIDER},
  {LPGEN("Category 1"),LI_LIST,            DBVT_ASCIIZ, "Past0", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGEN("Past Background 1"),LI_STRING,   DBVT_ASCIIZ, "Past0Text"},
  {LPGEN("Category 2"),LI_LIST,            DBVT_ASCIIZ, "Past1", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGEN("Past Background 2"),LI_STRING,   DBVT_ASCIIZ, "Past1Text"},
  {LPGEN("Category 3"),LI_LIST,            DBVT_ASCIIZ, "Past2", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGEN("Past Background 3"),LI_STRING,   DBVT_ASCIIZ, "Past2Text"},
  //affiliation
  {LPGEN("Affiliations"),                  LI_DIVIDER},
  {LPGEN("Affiliation category 1"),LI_LIST,DBVT_ASCIIZ, "Affiliation0", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGEN("Affiliation 1"),LI_STRING,       DBVT_ASCIIZ, "Affiliation0Text"},
  {LPGEN("Affiliation category 2"),LI_LIST,DBVT_ASCIIZ, "Affiliation1", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGEN("Affiliation 2"),LI_STRING,       DBVT_ASCIIZ, "Affiliation1Text"},
  {LPGEN("Affiliation category 3"),LI_LIST,DBVT_ASCIIZ, "Affiliation2", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGEN("Affiliation 3"),LI_STRING,       DBVT_ASCIIZ, "Affiliation2Text"}
};

const int settingCount=sizeof(setting)/sizeof(setting[0]);
