// ---------------------------------------------------------------------------80
//                ICQ plugin for Miranda Instant Messenger
//                ________________________________________
//
// Copyright © 2001-2004 Richard Hughes, Martin Öberg
// Copyright © 2004-2008 Joe Kucera, Bio
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// -----------------------------------------------------------------------------
//
// File name      : $URL$
// Revision       : $Revision$
// Last change on : $Date$
// Last change by : $Author$
//
// DESCRIPTION:
//
//  ChangeInfo Plugin stuff
//
// -----------------------------------------------------------------------------

#include "icqoscar.h"

static ListTypeDataItem countries[]={
  {0   ,LPGENUTF("Unspecified")},
  {9999,LPGENUTF("Other")},
  {93  ,LPGENUTF("Afghanistan")},
  {355 ,LPGENUTF("Albania")},
  {213 ,LPGENUTF("Algeria")},
  {684 ,LPGENUTF("American Samoa")},
  {376 ,LPGENUTF("Andorra")},
  {244 ,LPGENUTF("Angola")},
  {101 ,LPGENUTF("Anguilla")},
  {102 ,LPGENUTF("Antigua and Barbuda")},
  {5902,LPGENUTF("Antilles")},
  {54  ,LPGENUTF("Argentina")},
  {374 ,LPGENUTF("Armenia")},
  {297 ,LPGENUTF("Aruba")},
  {247 ,LPGENUTF("Ascension Island")},
  {61  ,LPGENUTF("Australia")},
  {43  ,LPGENUTF("Austria")},
  {994 ,LPGENUTF("Azerbaijan")},
  {103 ,LPGENUTF("Bahamas")},
  {973 ,LPGENUTF("Bahrain")},
  {880 ,LPGENUTF("Bangladesh")},
  {104 ,LPGENUTF("Barbados")},
  {120 ,LPGENUTF("Barbuda")},
  {375 ,LPGENUTF("Belarus")},
  {32  ,LPGENUTF("Belgium")},
  {501 ,LPGENUTF("Belize")},
  {229 ,LPGENUTF("Benin")},
  {105 ,LPGENUTF("Bermuda")},
  {975 ,LPGENUTF("Bhutan")},
  {591 ,LPGENUTF("Bolivia")},
  {387 ,LPGENUTF("Bosnia and Herzegovina")},
  {267 ,LPGENUTF("Botswana")},
  {55  ,LPGENUTF("Brazil")},
  {106 ,LPGENUTF("British Virgin Islands")},
  {673 ,LPGENUTF("Brunei")},
  {359 ,LPGENUTF("Bulgaria")},
  {226 ,LPGENUTF("Burkina Faso")},
  {257 ,LPGENUTF("Burundi")},
  {855 ,LPGENUTF("Cambodia")},
  {237 ,LPGENUTF("Cameroon")},
  {107 ,LPGENUTF("Canada")},
  {178 ,LPGENUTF("Canary Islands")},
  {238 ,LPGENUTF("Cape Verde Islands")},
  {108 ,LPGENUTF("Cayman Islands")},
  {236 ,LPGENUTF("Central African Republic")},
  {235 ,LPGENUTF("Chad")},
  {56  ,LPGENUTF("Chile, Republic of")},
  {86  ,LPGENUTF("China")},
  {672 ,LPGENUTF("Christmas Island")},
  {6101,LPGENUTF("Cocos-Keeling Islands")},
  {6102,LPGENUTF("Cocos (Keeling) Islands")},
  {57  ,LPGENUTF("Colombia")},
  {2691,LPGENUTF("Comoros")},
  {243 ,LPGENUTF("Congo, Democratic Republic of (Zaire)")},
  {242 ,LPGENUTF("Congo, Republic of the")},
  {682 ,LPGENUTF("Cook Islands")},
  {506 ,LPGENUTF("Costa Rica")},
  {225 ,LPGENUTF("Cote d'Ivoire (Ivory Coast)")},
  {385 ,LPGENUTF("Croatia")},
  {53  ,LPGENUTF("Cuba")},
  {357 ,LPGENUTF("Cyprus")},
  {420 ,LPGENUTF("Czech Republic")},
  {45  ,LPGENUTF("Denmark")},
  {246 ,LPGENUTF("Diego Garcia")},
  {253 ,LPGENUTF("Djibouti")},
  {109 ,LPGENUTF("Dominica")},
  {110 ,LPGENUTF("Dominican Republic")},
  {593 ,LPGENUTF("Ecuador")},
  {20  ,LPGENUTF("Egypt")},
  {503 ,LPGENUTF("El Salvador")},
  {240 ,LPGENUTF("Equatorial Guinea")},
  {291 ,LPGENUTF("Eritrea")},
  {372 ,LPGENUTF("Estonia")},
  {251 ,LPGENUTF("Ethiopia")},
  {298 ,LPGENUTF("Faeroe Islands")},
  {500 ,LPGENUTF("Falkland Islands")},
  {679 ,LPGENUTF("Fiji")},
  {358 ,LPGENUTF("Finland")},
  {33  ,LPGENUTF("France")},
  {5901,LPGENUTF("French Antilles")},
  {594 ,LPGENUTF("French Guiana")},
  {689 ,LPGENUTF("French Polynesia")},
  {241 ,LPGENUTF("Gabon")},
  {220 ,LPGENUTF("Gambia")},
  {995 ,LPGENUTF("Georgia")},
  {49  ,LPGENUTF("Germany")},
  {233 ,LPGENUTF("Ghana")},
  {350 ,LPGENUTF("Gibraltar")},
  {30  ,LPGENUTF("Greece")},
  {299 ,LPGENUTF("Greenland")},
  {111 ,LPGENUTF("Grenada")},
  {590 ,LPGENUTF("Guadeloupe")},
  {671 ,LPGENUTF("Guam, US Territory of")},
  {502 ,LPGENUTF("Guatemala")},
  {224 ,LPGENUTF("Guinea")},
  {245 ,LPGENUTF("Guinea-Bissau")},
  {592 ,LPGENUTF("Guyana")},
  {509 ,LPGENUTF("Haiti")},
  {504 ,LPGENUTF("Honduras")},
  {852 ,LPGENUTF("Hong Kong")},
  {36  ,LPGENUTF("Hungary")},
  {354 ,LPGENUTF("Iceland")},
  {91  ,LPGENUTF("India")},
  {62  ,LPGENUTF("Indonesia")},
  {98  ,LPGENUTF("Iran (Islamic Republic of)")},
  {964 ,LPGENUTF("Iraq")},
  {353 ,LPGENUTF("Ireland")},
  {972 ,LPGENUTF("Israel")},
  {39  ,LPGENUTF("Italy")},
  {112 ,LPGENUTF("Jamaica")},
  {81  ,LPGENUTF("Japan")},
  {962 ,LPGENUTF("Jordan")},
  {705 ,LPGENUTF("Kazakhstan")},
  {254 ,LPGENUTF("Kenya")},
  {686 ,LPGENUTF("Kiribati")},
  {850 ,LPGENUTF("Korea, North")},
  {82  ,LPGENUTF("Korea, South")},
  {965 ,LPGENUTF("Kuwait")},
  {706 ,LPGENUTF("Kyrgyzstan")},
  {856 ,LPGENUTF("Laos")},
  {371 ,LPGENUTF("Latvia")},
  {961 ,LPGENUTF("Lebanon")},
  {266 ,LPGENUTF("Lesotho")},
  {231 ,LPGENUTF("Liberia")},
  {218 ,LPGENUTF("Libyan Arab Jamahiriya")},
  {4101,LPGENUTF("Liechtenstein")},
  {370 ,LPGENUTF("Lithuania")},
  {352 ,LPGENUTF("Luxembourg")},
  {853 ,LPGENUTF("Macau")},
  {389 ,LPGENUTF("Macedonia (F.Y.R.O.M.)")},
  {261 ,LPGENUTF("Madagascar")},
  {265 ,LPGENUTF("Malawi")},
  {60  ,LPGENUTF("Malaysia")},
  {960 ,LPGENUTF("Maldives")},
  {223 ,LPGENUTF("Mali")},
  {356 ,LPGENUTF("Malta")},
  {692 ,LPGENUTF("Marshall Islands")},
  {596 ,LPGENUTF("Martinique")},
  {222 ,LPGENUTF("Mauritania")},
  {230 ,LPGENUTF("Mauritius")},
  {269 ,LPGENUTF("Mayotte Island")},
  {52  ,LPGENUTF("Mexico")},
  {691 ,LPGENUTF("Micronesia, Federated States of")},
  {373 ,LPGENUTF("Moldova, Republic of")},
  {377 ,LPGENUTF("Monaco")},
  {976 ,LPGENUTF("Mongolia")},
  {113 ,LPGENUTF("Montserrat")},
  {212 ,LPGENUTF("Morocco")},
  {258 ,LPGENUTF("Mozambique")},
  {95  ,LPGENUTF("Myanmar")},
  {264 ,LPGENUTF("Namibia")},
  {674 ,LPGENUTF("Nauru")},
  {977 ,LPGENUTF("Nepal")},
  {31  ,LPGENUTF("Netherlands")},
  {599 ,LPGENUTF("Netherlands Antilles")},
  {114 ,LPGENUTF("Nevis")},
  {687 ,LPGENUTF("New Caledonia")},
  {64  ,LPGENUTF("New Zealand")},
  {505 ,LPGENUTF("Nicaragua")},
  {227 ,LPGENUTF("Niger")},
  {234 ,LPGENUTF("Nigeria")},
  {683 ,LPGENUTF("Niue")},
  {6722,LPGENUTF("Norfolk Island")},
  {47  ,LPGENUTF("Norway")},
  {968 ,LPGENUTF("Oman")},
  {92  ,LPGENUTF("Pakistan")},
  {680 ,LPGENUTF("Palau")},
  {507 ,LPGENUTF("Panama")},
  {675 ,LPGENUTF("Papua New Guinea")},
  {595 ,LPGENUTF("Paraguay")},
  {51  ,LPGENUTF("Peru")},
  {63  ,LPGENUTF("Philippines")},
  {48  ,LPGENUTF("Poland")},
  {351 ,LPGENUTF("Portugal")},
  {121 ,LPGENUTF("Puerto Rico")},
  {974 ,LPGENUTF("Qatar")},
  {262 ,LPGENUTF("Reunion Island")},
  {40  ,LPGENUTF("Romania")},
  {6701,LPGENUTF("Rota Island")},
  {7   ,LPGENUTF("Russia")},
  {250 ,LPGENUTF("Rwanda")},
  {290 ,LPGENUTF("Saint Helena")},
  {115 ,LPGENUTF("Saint Kitts")},
  {1141,LPGENUTF("Saint Kitts and Nevis")},
  {122 ,LPGENUTF("Saint Lucia")},
  {508 ,LPGENUTF("Saint Pierre and Miquelon")},
  {116 ,LPGENUTF("Saint Vincent and the Grenadines")},
  {670 ,LPGENUTF("Saipan Island")},
  {378 ,LPGENUTF("San Marino")},
  {239 ,LPGENUTF("Sao Tome and Principe")},
  {966 ,LPGENUTF("Saudi Arabia")},
  {442 ,LPGENUTF("Scotland")},
  {221 ,LPGENUTF("Senegal")},
  {248 ,LPGENUTF("Seychelles")},
  {232 ,LPGENUTF("Sierra Leone")},
  {65  ,LPGENUTF("Singapore")},
  {421 ,LPGENUTF("Slovakia")},
  {386 ,LPGENUTF("Slovenia")},
  {677 ,LPGENUTF("Solomon Islands")},
  {252 ,LPGENUTF("Somalia")},
  {27  ,LPGENUTF("South Africa")},
  {34  ,LPGENUTF("Spain")},
  {94  ,LPGENUTF("Sri Lanka")},
  {249 ,LPGENUTF("Sudan")},
  {597 ,LPGENUTF("Suriname")},
  {268 ,LPGENUTF("Swaziland")},
  {46  ,LPGENUTF("Sweden")},
  {41  ,LPGENUTF("Switzerland")},
  {963 ,LPGENUTF("Syrian Arab Republic")},
  {886 ,LPGENUTF("Taiwan")},
  {708 ,LPGENUTF("Tajikistan")},
  {255 ,LPGENUTF("Tanzania")},
  {66  ,LPGENUTF("Thailand")},
  {6702,LPGENUTF("Tinian Island")},
  {228 ,LPGENUTF("Togo")},
  {690 ,LPGENUTF("Tokelau")},
  {676 ,LPGENUTF("Tonga")},
  {117 ,LPGENUTF("Trinidad and Tobago")},
  {216 ,LPGENUTF("Tunisia")},
  {90  ,LPGENUTF("Turkey")},
  {709 ,LPGENUTF("Turkmenistan")},
  {118 ,LPGENUTF("Turks and Caicos Islands")},
  {688 ,LPGENUTF("Tuvalu")},
  {256 ,LPGENUTF("Uganda")},
  {380 ,LPGENUTF("Ukraine")},
  {971 ,LPGENUTF("United Arab Emirates")},
  {44  ,LPGENUTF("United Kingdom")},
  {598 ,LPGENUTF("Uruguay")},
  {1   ,LPGENUTF("USA")},
  {711 ,LPGENUTF("Uzbekistan")},
  {678 ,LPGENUTF("Vanuatu")},
  {379 ,LPGENUTF("Vatican City")},
  {58  ,LPGENUTF("Venezuela")},
  {84  ,LPGENUTF("Vietnam")},
  {123 ,LPGENUTF("Virgin Islands (USA)")},
  {441 ,LPGENUTF("Wales")},
  {681 ,LPGENUTF("Wallis and Futuna Islands")},
  {685 ,LPGENUTF("Western Samoa")},
  {967 ,LPGENUTF("Yemen")},
  {381 ,LPGENUTF("Yugoslavia")},
  {3811,LPGENUTF("Yugoslavia - Serbia")},
  {382 ,LPGENUTF("Yugoslavia - Montenegro")},
  {260 ,LPGENUTF("Zambia")},
  {263 ,LPGENUTF("Zimbabwe")},
};

static ListTypeDataItem timezones[]={
  {-100,LPGENUTF("Unspecified")},
  {24  ,LPGENUTF("GMT-12:00 Eniwetok; Kwajalein")},
  {23  ,LPGENUTF("GMT-11:30")},
  {22  ,LPGENUTF("GMT-11:00 Midway Island; Samoa")},
  {21  ,LPGENUTF("GMT-10:30")},
  {20  ,LPGENUTF("GMT-10:00 Hawaii")},
  {19  ,LPGENUTF("GMT-9:30")},
  {18  ,LPGENUTF("GMT-9:00 Alaska")},
  {17  ,LPGENUTF("GMT-8:30")},
  {16  ,LPGENUTF("GMT-8:00 Pacific Time; Tijuana")},
  {15  ,LPGENUTF("GMT-7:30")},
  {14  ,LPGENUTF("GMT-7:00 Arizona; Mountain Time")},
  {13  ,LPGENUTF("GMT-6:30")},
  {12  ,LPGENUTF("GMT-6:00 Central Time; Central America; Saskatchewan")},
  {11  ,LPGENUTF("GMT-5:30")},
  {10  ,LPGENUTF("GMT-5:00 Eastern Time; Bogota; Lima; Quito")},
  {9   ,LPGENUTF("GMT-4:30")},
  {8   ,LPGENUTF("GMT-4:00 Atlantic Time; Santiago; Caracas; La Paz")},
  {7   ,LPGENUTF("GMT-3:30 Newfoundland")},
  {6   ,LPGENUTF("GMT-3:00 Greenland; Buenos Aires; Georgetown")},
  {5   ,LPGENUTF("GMT-2:30")},
  {4   ,LPGENUTF("GMT-2:00 Mid-Atlantic")},
  {3   ,LPGENUTF("GMT-1:30")},
  {2   ,LPGENUTF("GMT-1:00 Cape Verde Islands; Azores")},
  {1   ,LPGENUTF("GMT-0:30")},
  {0   ,LPGENUTF("GMT+0:00 London; Dublin; Edinburgh; Lisbon; Casablanca")},
  {-1  ,LPGENUTF("GMT+0:30")},
  {-2  ,LPGENUTF("GMT+1:00 Central European Time; West Central Africa; Warsaw")},
  {-3  ,LPGENUTF("GMT+1:30")},
  {-4  ,LPGENUTF("GMT+2:00 Jerusalem; Helsinki; Harare; Cairo; Bucharest; Athens")},
  {-5  ,LPGENUTF("GMT+2:30")},
  {-6  ,LPGENUTF("GMT+3:00 Moscow; St. Petersburg; Nairobi; Kuwait; Baghdad")},
  {-7  ,LPGENUTF("GMT+3:30 Tehran")},
  {-8  ,LPGENUTF("GMT+4:00 Baku; Tbilisi; Yerevan; Abu Dhabi; Muscat")},
  {-9  ,LPGENUTF("GMT+4:30 Kabul")},
  {-10 ,LPGENUTF("GMT+5:00 Calcutta; Chennai; Mumbai; New Delhi; Ekaterinburg")},
  {-11 ,LPGENUTF("GMT+5:30")},
  {-12 ,LPGENUTF("GMT+6:00 Astana; Dhaka; Almaty; Novosibirsk; Sri Jayawardenepura")},
  {-13 ,LPGENUTF("GMT+6:30 Rangoon")},
  {-14 ,LPGENUTF("GMT+7:00 Bankok; Hanoi; Jakarta; Krasnoyarsk")},
  {-15 ,LPGENUTF("GMT+7:30")},
  {-16 ,LPGENUTF("GMT+8:00 Perth; Taipei; Singapore; Hong Kong; Beijing")},
  {-17 ,LPGENUTF("GMT+8:30")},
  {-18 ,LPGENUTF("GMT+9:00 Tokyo; Osaka; Seoul; Sapporo; Yakutsk")},
  {-19 ,LPGENUTF("GMT+9:30 Darwin; Adelaide")},
  {-20 ,LPGENUTF("GMT+10:00 East Australia; Guam; Vladivostok")},
  {-21 ,LPGENUTF("GMT+10:30")},
  {-22 ,LPGENUTF("GMT+11:00 Magadan; Solomon Is.; New Caledonia")},
  {-23 ,LPGENUTF("GMT+11:30")},
  {-24 ,LPGENUTF("GMT+12:00 Auckland; Wellington; Fiji; Kamchatka; Marshall Is.")},
};

static ListTypeDataItem occupations[] = {
  {0, LPGENUTF("Unspecified")},
  {1, LPGENUTF("Academic")},
  {2, LPGENUTF("Administrative")},
  {3, LPGENUTF("Art/Entertainment")},
  {4, LPGENUTF("College Student")},
  {5, LPGENUTF("Computers")},
  {6, LPGENUTF("Community & Social")},
  {7, LPGENUTF("Education")},
  {8, LPGENUTF("Engineering")},
  {9, LPGENUTF("Financial Services")},
  {10, LPGENUTF("Government")},
  {11, LPGENUTF("High School Student")},
  {12, LPGENUTF("Home")},
  {13, LPGENUTF("ICQ - Providing Help")},
  {14, LPGENUTF("Law")},
  {15, LPGENUTF("Managerial")},
  {16, LPGENUTF("Manufacturing")},
  {17, LPGENUTF("Medical/Health")},
  {18, LPGENUTF("Military")},
  {19, LPGENUTF("Non-Government Organization")},
  {20, LPGENUTF("Professional")},
  {21, LPGENUTF("Retail")},
  {22, LPGENUTF("Retired")},
  {23, LPGENUTF("Science & Research")},
  {24, LPGENUTF("Sports")},
  {25, LPGENUTF("Technical")},
  {26, LPGENUTF("University Student")},
  {27, LPGENUTF("Web Building")},
  {99, LPGENUTF("Other Services")}
};

static ListTypeDataItem genders[]={
  {0,LPGENUTF("Unspecified")},
  {'M',LPGENUTF("Male")},
  {'F',LPGENUTF("Female")},
};

static ListTypeDataItem months[]={
  {0, LPGENUTF("Unspecified")},
  {1, LPGENUTF("January")},
  {2, LPGENUTF("February")},
  {3, LPGENUTF("March")},
  {4, LPGENUTF("April")},
  {5, LPGENUTF("May")},
  {6, LPGENUTF("June")},
  {7, LPGENUTF("July")},
  {8, LPGENUTF("August")},
  {9, LPGENUTF("September")},
  {10,LPGENUTF("October")},
  {11,LPGENUTF("November")},
  {12,LPGENUTF("December")},
};

static ListTypeDataItem languages[]={
  {0, LPGENUTF("None")},
  {55,LPGENUTF("Afrikaans")},
  {58,LPGENUTF("Albanian")},
  {1, LPGENUTF("Arabic")},
  {59,LPGENUTF("Armenian")},
  {68,LPGENUTF("Azerbaijani")},
  {72,LPGENUTF("Belorussian")},
  {2, LPGENUTF("Bhojpuri")},
  {56,LPGENUTF("Bosnian")},
  {3, LPGENUTF("Bulgarian")},
  {4, LPGENUTF("Burmese")},
  {5, LPGENUTF("Cantonese")},
  {6, LPGENUTF("Catalan")},
  {61,LPGENUTF("Chamorro")},
  {7, LPGENUTF("Chinese")},
  {8, LPGENUTF("Croatian")},
  {9, LPGENUTF("Czech")},
  {10,LPGENUTF("Danish")},
  {11,LPGENUTF("Dutch")},
  {12,LPGENUTF("English")},
  {13,LPGENUTF("Esperanto")},
  {14,LPGENUTF("Estonian")},
  {15,LPGENUTF("Farci")},
  {16,LPGENUTF("Finnish")},
  {17,LPGENUTF("French")},
  {18,LPGENUTF("Gaelic")},
  {19,LPGENUTF("German")},
  {20,LPGENUTF("Greek")},
  {70,LPGENUTF("Gujarati")},
  {21,LPGENUTF("Hebrew")},
  {22,LPGENUTF("Hindi")},
  {23,LPGENUTF("Hungarian")},
  {24,LPGENUTF("Icelandic")},
  {25,LPGENUTF("Indonesian")},
  {26,LPGENUTF("Italian")},
  {27,LPGENUTF("Japanese")},
  {28,LPGENUTF("Khmer")},
  {29,LPGENUTF("Korean")},
  {69,LPGENUTF("Kurdish")},
  {30,LPGENUTF("Lao")},
  {31,LPGENUTF("Latvian")},
  {32,LPGENUTF("Lithuanian")},
  {65,LPGENUTF("Macedonian")},
  {33,LPGENUTF("Malay")},
  {63,LPGENUTF("Mandarin")},
  {62,LPGENUTF("Mongolian")},
  {34,LPGENUTF("Norwegian")},
  {57,LPGENUTF("Persian")},
  {35,LPGENUTF("Polish")},
  {36,LPGENUTF("Portuguese")},
  {60,LPGENUTF("Punjabi")},
  {37,LPGENUTF("Romanian")},
  {38,LPGENUTF("Russian")},
  {39,LPGENUTF("Serbo-Croatian")},
  {66,LPGENUTF("Sindhi")},
  {40,LPGENUTF("Slovak")},
  {41,LPGENUTF("Slovenian")},
  {42,LPGENUTF("Somali")},
  {43,LPGENUTF("Spanish")},
  {44,LPGENUTF("Swahili")},
  {45,LPGENUTF("Swedish")},
  {46,LPGENUTF("Tagalog")},
  {64,LPGENUTF("Taiwaness")},
  {71,LPGENUTF("Tamil")},
  {47,LPGENUTF("Tatar")},
  {48,LPGENUTF("Thai")},
  {49,LPGENUTF("Turkish")},
  {50,LPGENUTF("Ukrainian")},
  {51,LPGENUTF("Urdu")},
  {52,LPGENUTF("Vietnamese")},
  {67,LPGENUTF("Welsh")},
  {53,LPGENUTF("Yiddish")},
  {54,LPGENUTF("Yoruba")},
};

static ListTypeDataItem interests[]={
  {0, LPGENUTF("Unspecified")},
  {100, LPGENUTF("Art")},
  {101, LPGENUTF("Cars")},
  {102, LPGENUTF("Celebrity Fans")},
  {103, LPGENUTF("Collections")},
  {104, LPGENUTF("Computers")},
  {105, LPGENUTF("Culture & Literature")},
  {106, LPGENUTF("Fitness")},
  {107, LPGENUTF("Games")},
  {108, LPGENUTF("Hobbies")},
  {109, LPGENUTF("ICQ - Providing Help")},
  {110, LPGENUTF("Internet")},
  {111, LPGENUTF("Lifestyle")},
  {112, LPGENUTF("Movies/TV")},
  {113, LPGENUTF("Music")},
  {114, LPGENUTF("Outdoor Activities")},
  {115, LPGENUTF("Parenting")},
  {116, LPGENUTF("Pets/Animals")},
  {117, LPGENUTF("Religion")},
  {118, LPGENUTF("Science/Technology")},
  {119, LPGENUTF("Skills")},
  {120, LPGENUTF("Sports")},
  {121, LPGENUTF("Web Design")},
  {122, LPGENUTF("Nature and Environment")},
  {123, LPGENUTF("News & Media")},
  {124, LPGENUTF("Government")},
  {125, LPGENUTF("Business & Economy")},
  {126, LPGENUTF("Mystics")},
  {127, LPGENUTF("Travel")},
  {128, LPGENUTF("Astronomy")},
  {129, LPGENUTF("Space")},
  {130, LPGENUTF("Clothing")},
  {131, LPGENUTF("Parties")},
  {132, LPGENUTF("Women")},
  {133, LPGENUTF("Social science")},
  {134, LPGENUTF("60's")},
  {135, LPGENUTF("70's")},
  {136, LPGENUTF("80's")},
  {137, LPGENUTF("50's")},
  {138, LPGENUTF("Finance and corporate")},
  {139, LPGENUTF("Entertainment")},
  {140, LPGENUTF("Consumer electronics")},
  {141, LPGENUTF("Retail stores")},
  {142, LPGENUTF("Health and beauty")},
  {143, LPGENUTF("Media")},
  {144, LPGENUTF("Household products")},
  {145, LPGENUTF("Mail order catalog")},
  {146, LPGENUTF("Business services")},
  {147, LPGENUTF("Audio and visual")},
  {148, LPGENUTF("Sporting and athletic")},
  {149, LPGENUTF("Publishing")},
  {150, LPGENUTF("Home automation")}
};

static ListTypeDataItem pastbackground[]={
  {0,   LPGENUTF("Unspecified")},
  {300, LPGENUTF("Elementary School")},
  {301, LPGENUTF("High School")},
  {302, LPGENUTF("College")},
  {303, LPGENUTF("University")},
  {304, LPGENUTF("Military")},
  {305, LPGENUTF("Past Work Place")},
  {306, LPGENUTF("Past Organization")},
  {399, LPGENUTF("Other")}
};

static ListTypeDataItem affiliation[]={
  {0,   LPGENUTF("Unspecified")},
  {200, LPGENUTF("Alumni Org.")},
  {201, LPGENUTF("Charity Org.")},
  {202, LPGENUTF("Club/Social Org.")},
  {203, LPGENUTF("Community Org.")},
  {204, LPGENUTF("Cultural Org.")},
  {205, LPGENUTF("Fan Clubs")},
  {206, LPGENUTF("Fraternity/Sorority")},
  {207, LPGENUTF("Hobbyists Org.")},
  {208, LPGENUTF("International Org.")},
  {209, LPGENUTF("Nature and Environment Org.")},
  {210, LPGENUTF("Professional Org.")},
  {211, LPGENUTF("Scientific/Technical Org.")},
  {212, LPGENUTF("Self Improvement Group")},
  {213, LPGENUTF("Spiritual/Religious Org.")},
  {214, LPGENUTF("Sports Org.")},
  {215, LPGENUTF("Support Org.")},
  {216, LPGENUTF("Trade and Business Org.")},
  {217, LPGENUTF("Union")},
  {218, LPGENUTF("Volunteer Org.")},
  {299, LPGENUTF("Other")},
};

static ListTypeDataItem maritalstatuses[]={
  {0,  LPGENUTF("Unspecified")},
  {10, LPGENUTF("Single")},
  {11, LPGENUTF("Close relationships")},
  {12, LPGENUTF("Engaged")},
  {20, LPGENUTF("Married")},
  {30, LPGENUTF("Divorced")},
  {31, LPGENUTF("Separated")},
  {40, LPGENUTF("Widowed")}
};


const int ageRange[]={13,0x7FFF};  // 14, 130
const int yearRange[]={1753,0x7FFF}; // 1880, 2000
const int dayRange[]={1,31};


SettingItem setting[]={
  //personal
  {LPGENUTF("Personal"),       LI_DIVIDER},
  {LPGENUTF("Nickname"),       LI_STRING,     DBVT_ASCIIZ, "Nick"},
  {LPGENUTF("First name"),     LI_STRING,     DBVT_ASCIIZ, "FirstName"},
  {LPGENUTF("Last name"),      LI_STRING,     DBVT_ASCIIZ, "LastName"},
  {LPGENUTF("Age"),            LI_NUMBER,     DBVT_WORD,   "Age",        (void*)ageRange},
  {LPGENUTF("Gender"),         LI_LIST,       DBVT_BYTE,   "Gender",     genders, sizeof(genders)/sizeof(genders[0])},
  {LPGENUTF("About"),          LI_LONGSTRING, DBVT_ASCIIZ, "About"},
  //password
  {LPGENUTF("Password"),       LI_DIVIDER},
  {LPGENUTF("Password"),       LI_STRING|LIF_PASSWORD,DBVT_ASCIIZ, "Password"},
  //contact
  {LPGENUTF("Contact"),        LI_DIVIDER},
  {LPGENUTF("Primary e-mail"), LI_STRING,     DBVT_ASCIIZ, "e-mail"},
  {LPGENUTF("Secondary e-mail"), LI_STRING,   DBVT_ASCIIZ, "e-mail0"},
  {LPGENUTF("Tertiary e-mail"), LI_STRING,    DBVT_ASCIIZ, "e-mail1"},
  {LPGENUTF("Homepage"),       LI_STRING,     DBVT_ASCIIZ, "Homepage"},
  {LPGENUTF("Street"),         LI_STRING,     DBVT_ASCIIZ, "Street"},
  {LPGENUTF("City"),           LI_STRING,     DBVT_ASCIIZ, "City"},
  {LPGENUTF("State"),          LI_STRING,     DBVT_ASCIIZ, "State"},
  {LPGENUTF("ZIP/postcode"),   LI_STRING,     DBVT_ASCIIZ, "ZIP"},
  {LPGENUTF("Country"),        LI_LIST,       DBVT_WORD,   "Country",    countries, sizeof(countries)/sizeof(countries[0])},
  {LPGENUTF("Phone number"),   LI_STRING,     DBVT_ASCIIZ, "Phone"},
  {LPGENUTF("Fax number"),     LI_STRING,     DBVT_ASCIIZ, "Fax"},
  {LPGENUTF("Cellular number"),LI_STRING,     DBVT_ASCIIZ, "Cellular"},
  //more
  {LPGENUTF("Personal Detail"),LI_DIVIDER},
  {LPGENUTF("Timezone"),       LI_LIST|LIF_ZEROISVALID|LIF_SIGNED,DBVT_BYTE,   "Timezone", timezones, sizeof(timezones)/sizeof(timezones[0])},
  {LPGENUTF("Year of birth"),  LI_NUMBER,     DBVT_WORD,   "BirthYear",  (void*)yearRange},
  {LPGENUTF("Month of birth"), LI_LIST,       DBVT_BYTE,   "BirthMonth", months, sizeof(months)/sizeof(months[0])},
  {LPGENUTF("Day of birth"),   LI_NUMBER,     DBVT_BYTE,   "BirthDay",   (void*)dayRange},
  {LPGENUTF("Marital Status"), LI_LIST,       DBVT_BYTE,   "MaritalStatus", maritalstatuses, sizeof(maritalstatuses)/sizeof(maritalstatuses[0])},
  {LPGENUTF("Spoken language 1"), LI_LIST,    DBVT_ASCIIZ, "Language1",  languages, sizeof(languages)/sizeof(languages[0])},
  {LPGENUTF("Spoken language 2"), LI_LIST,    DBVT_ASCIIZ, "Language2",  languages, sizeof(languages)/sizeof(languages[0])},
  {LPGENUTF("Spoken language 3"), LI_LIST,    DBVT_ASCIIZ, "Language3",  languages, sizeof(languages)/sizeof(languages[0])},
  //more
  {LPGENUTF("Originally from"),LI_DIVIDER},
  {LPGENUTF("City"),           LI_STRING,     DBVT_ASCIIZ, "OriginCity"},
  {LPGENUTF("State"),          LI_STRING,     DBVT_ASCIIZ, "OriginState"},
  {LPGENUTF("Country"),        LI_LIST,       DBVT_WORD,   "OriginCountry",    countries, sizeof(countries)/sizeof(countries[0])},
  //work
  {LPGENUTF("Work"),           LI_DIVIDER},
  {LPGENUTF("Company name"),   LI_STRING,     DBVT_ASCIIZ, "Company"},
  {LPGENUTF("Company homepage"),LI_STRING,    DBVT_ASCIIZ, "CompanyHomepage"},
  {LPGENUTF("Company street"), LI_STRING,     DBVT_ASCIIZ, "CompanyStreet"},
  {LPGENUTF("Company city"),   LI_STRING,     DBVT_ASCIIZ, "CompanyCity"},
  {LPGENUTF("Company state"),  LI_STRING,     DBVT_ASCIIZ, "CompanyState"},
  {LPGENUTF("Company phone"),  LI_STRING,     DBVT_ASCIIZ, "CompanyPhone"},
  {LPGENUTF("Company fax"),    LI_STRING,     DBVT_ASCIIZ, "CompanyFax"},
  {LPGENUTF("Company ZIP/postcode"),LI_STRING,DBVT_ASCIIZ, "CompanyZIP"},
  {LPGENUTF("Company country"),LI_LIST,       DBVT_WORD,   "CompanyCountry",countries, sizeof(countries)/sizeof(countries[0])},
  {LPGENUTF("Company department"),LI_STRING,  DBVT_ASCIIZ, "CompanyDepartment"},
  {LPGENUTF("Company position"),LI_STRING,    DBVT_ASCIIZ, "CompanyPosition"},
  {LPGENUTF("Company occupation"),LI_LIST,    DBVT_WORD,   "CompanyOccupation", occupations, sizeof(occupations)/sizeof(occupations[0])},
  //interests
  {LPGENUTF("Personal Interests"),            LI_DIVIDER},
  {LPGENUTF("Interest category 1"),LI_LIST,   DBVT_ASCIIZ, "Interest0Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGENUTF("Interest areas 1"),LI_STRING,    DBVT_ASCIIZ, "Interest0Text"},
  {LPGENUTF("Interest category 2"),LI_LIST,   DBVT_ASCIIZ, "Interest1Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGENUTF("Interest areas 2"),LI_STRING,    DBVT_ASCIIZ, "Interest1Text"},
  {LPGENUTF("Interest category 3"),LI_LIST,   DBVT_ASCIIZ, "Interest2Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGENUTF("Interest areas 3"),LI_STRING,    DBVT_ASCIIZ, "Interest2Text"},
  {LPGENUTF("Interest category 4"),LI_LIST,   DBVT_ASCIIZ, "Interest3Cat", interests, sizeof(interests)/sizeof(interests[0])},
  {LPGENUTF("Interest areas 4"),LI_STRING,    DBVT_ASCIIZ, "Interest3Text"},
  //pastbackground
  {LPGENUTF("Past Background"),               LI_DIVIDER},
  {LPGENUTF("Category 1"),LI_LIST,            DBVT_ASCIIZ, "Past0", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGENUTF("Past Background 1"),LI_STRING,   DBVT_ASCIIZ, "Past0Text"},
  {LPGENUTF("Category 2"),LI_LIST,            DBVT_ASCIIZ, "Past1", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGENUTF("Past Background 2"),LI_STRING,   DBVT_ASCIIZ, "Past1Text"},
  {LPGENUTF("Category 3"),LI_LIST,            DBVT_ASCIIZ, "Past2", pastbackground, sizeof(pastbackground)/sizeof(pastbackground[0])},
  {LPGENUTF("Past Background 3"),LI_STRING,   DBVT_ASCIIZ, "Past2Text"},
  //affiliation
  {LPGENUTF("Affiliations"),                  LI_DIVIDER},
  {LPGENUTF("Affiliation category 1"),LI_LIST,DBVT_ASCIIZ, "Affiliation0", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGENUTF("Affiliation 1"),LI_STRING,       DBVT_ASCIIZ, "Affiliation0Text"},
  {LPGENUTF("Affiliation category 2"),LI_LIST,DBVT_ASCIIZ, "Affiliation1", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGENUTF("Affiliation 2"),LI_STRING,       DBVT_ASCIIZ, "Affiliation1Text"},
  {LPGENUTF("Affiliation category 3"),LI_LIST,DBVT_ASCIIZ, "Affiliation2", affiliation, sizeof(affiliation)/sizeof(affiliation[0])},
  {LPGENUTF("Affiliation 3"),LI_STRING,       DBVT_ASCIIZ, "Affiliation2Text"}
};

const int settingCount=sizeof(setting)/sizeof(setting[0]);
