//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDC_AUTHICON                    1
#define IDD_OPT_VIEWMODES               1
#define IDD_DIALOG1                     3
#define IDD_OPT_FLOATING                3
#define IDD_DIALOG2                     4
#define IDD_OPT_SKIN                    4
#define IDD_QUICKIGNORE                 5
#define IDD_OPT                         6
#define IDD_OPTIONSDIALOG               101
#define IDI_MIRANDA                     102
#define IDD_CLNABOUT                    102
#define IDD_ABOUT                       103
#define IDI_ONLINE                      104
#define IDI_OFFLINE                     105
#define IDD_FILESEND                    107
#define IDD_FINDADD                     108
#define IDD_OPT_AUTOAWAY                109
#define IDD_GNUPL                       110
#define IDD_OPT_ICONS                   111
#define IDD_OPT_IGNORE                  112
#define IDD_OPT_PLUGINS                 113
#define IDD_OPT_VISIBILITY              114
#define IDD_ADDED                       115
#define IDD_OPTIONS                     116
#define IDD_READAWAYMSG                 117
#define IDD_SETAWAYMSG                  118
#define IDD_URLSEND                     119
#define IDD_URLRECV                     120
#define IDD_AUTHREQ                     121
#define IDD_DETAILS                     125
#define IDD_OPT_CLIST                   126
#define IDD_HISTORY                     127
#define IDI_AWAY                        128
#define IDI_FREE4CHAT                   129
#define IDI_INVISIBLE                   130
#define IDI_NA                          131
#define IDI_DETAILSLOGO                 133
#define IDD_OPT_SOUND                   134
#define IDI_SENDURL                     135
#define IDI_RECVMSG                     136
#define IDI_SENDMSG                     137
#define IDI_EMPTYBLOB                   139
#define IDI_FILE                        140
#define IDI_GROUPOPEN                   141
#define IDI_GROUPSHUT                   142
#define IDI_NOTICK                      143
#define IDI_ONTHEPHONE                  144
#define IDI_TICK                        146
#define IDI_USERONLINE                  147
#define IDM_COPY                        148
#define IDI_DND                         158
#define IDI_OCCUPIED                    159
#define IDI_USERDETAILS                 160
#define IDI_FINDUSER                    161
#define IDI_HELP                        162
#define IDI_OPTIONS                     163
#define IDI_MIRANDAWEBSITE              172
#define IDI_RENAME                      173
#define IDI_HISTORY                     174
#define IDI_DELETE                      175
#define IDI_CLVM_OPTIONS                176
#define IDI_CLVM_SELECT                 177
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDD_OPT_HOTKEY                  184
#define IDD_HISTORY_FIND                192
#define IDI_SENDEMAIL                   193
#define IDD_FILERECV                    194
#define IDD_PROFILEMANAGER              197
#define IDD_NEWPROFILE                  198
#define IDR_CLISTMENU                   199
#define IDI_BLANK                       200
#define IDD_PLUGINCONFLICT              204
#define IDI_TIMESTAMP                   208
#define IDI_CHANGEFONT                  209
#define IDI_ADDCONTACT                  210
#define IDI_SMALLDOT                    211
#define IDI_FILLEDBLOB                  212
#define IDC_HYPERLINKHAND               214
#define IDC_DROPUSER                    215
#define IDD_OPT_AWAYMSG                 217
#define IDD_OPT_CLUI                    218
#define IDD_OPT_XICONS                  219
#define IDD_INFO_SUMMARY                220
#define IDD_INFO_CONTACT                221
#define IDD_INFO_BACKGROUND             222
#define IDD_INFO_NOTES                  223
#define IDD_ADDEMAIL                    226
#define IDD_ICONINDEX                   227
#define IDD_OPT_CLC                     228
#define IDD_OPT_CLCTEXT                 229
#define IDD_OPT_CLCBKG                  230
#define IDD_INFO_LOCATION               231
#define IDD_INFO_WORK                   232
#define IDD_ADDPHONE                    233
#define IDD_OPT_SBAR                    234
#define IDD_INSTALLINI                  235
#define IDD_WARNINICHANGE               236
#define IDD_INIIMPORTDONE               237
#define IDB_SORTCOLUP                   239
#define IDB_SORTCOLDOWN                 240
#define IDB_XSTATUSIMAGES               241
#define IDD_OPT_NETLIB                  246
#define IDD_NETLIBLOGOPTS               247
#define IDD_FILETRANSFERINFO            249
#define IDD_OPT_FILETRANSFER            250
#define IDD_FILEEXISTS                  251
#define IDD_DELETECONTACT               254
#define IDD_DENYREASON                  256
#define IDD_ADDCONTACT                  257
#define IDD_OPT_CONTACT                 261
#define IDI_MULTISEND                   263
#define IDI_DOWNARROW                   264
#define IDD_CREDITS                     265
#define IDD_OPT_IDLE                    268
#define IDD_OPT_DSPPROFILES             300
#define IDD_OPT_DSPADVANCED             301
#define IDD_OPT_DSPITEMS                302
#define IDD_OPT_DSPGROUPS               303
#define IDC_ACTIVEPERC                  1000
#define IDC_RESETPROTOCOLDATA           1000
#define IDC_OPTIONSTAB                  1000
#define IDC_SAVE                        1001
#define IDC_ADD                         1002
#define IDI_OUTTOLUNCH                  1003
#define IDC_AUTOCLOSE                   1004
#define IDC_AGE                         1005
#define IDC_ALLFILESGROUP               1006
#define IDC_ALLICON                     1007
#define IDC_ALLSPEED                    1008
#define IDC_ALWAYSSTATUS                1009
#define IDC_STATIC23                    1010
#define IDC_APPLY                       1011
#define IDC_AUTOMIN                     1012
#define IDC_AUTOSIZE                    1013
#define IDC_AUTOSIZEUPWARD              1014
#define IDC_AVATARSIZESPIN              1015
#define IDC_AVATARSROUNDED2             1016
#define IDC_BORDERTYPE                  1017
#define IDC_CHANGE                      1018
#define IDC_TEXT                        1019
#define IDC_CHECK1                      1020
#define IDC_SKINMODE                    1020
#define IDC_FULLTRANSPARENT             1020
#define IDC_STATUSICONSCENTERED         1020
#define IDC_NOTRAYINFOTIPS              1020
#define IDC_SHOWXSTATUS                 1020
#define IDC_AUTOCLEAR                   1020
#define IDC_FLT_SIMPLELAYOUT            1020
#define IDC_USESKIN                     1020
#define IDC_IGN_MSGEVENTS               1020
#define IDC_AUTOCLEARVAL                1021
#define IDC_MARKLOCKED                  1021
#define IDC_IGN_FILEEVENTS              1021
#define IDC_AUTOCLEARSPIN               1022
#define IDC_CHOOSE                      1022
#define IDC_IGN_URLEVENTS               1022
#define IDC_COMPANY                     1023
#define IDC_LASTMSG                     1023
#define IDC_IGN_AUTH                    1023
#define IDC_SHOWNAMES                   1024
#define IDC_IGN_ADD                     1024
#define IDC_CONFIRMDELETE               1025
#define IDC_IGN_ONLINE                  1025
#define IDC_CURRENTTRANSFERRED          1026
#define IDC_IGN_ALWAYSONLINE            1026
#define IDC_DATE                        1027
#define IDC_IGN_ALWAYSOFFLINE           1027
#define IDC_DEPARTMENT                  1028
#define IDC_IGN_ONLINE2                 1028
#define IDC_IGN_PRIORITY                1028
#define IDC_DETAILS                     1029
#define IDC_DISABLEGROUPS               1030
#define IDC_DOBYEAR                     1031
#define IDC_ABOUT                       1032
#define IDC_MYNOTES                     1033
#define IDC_DONTREPLY                   1034
#define IDC_DROPSHADOW                  1035
#define IDC_URLS                        1037
#define IDC_DUMPRECV                    1038
#define IDC_REPLY                       1039
#define IDC_EQUALSELECTION              1040
#define IDC_URL                         1041
#define IDC_EQUALSELECTION2             1041
#define IDC_USEPERPROTO                 1041
#define IDC_EVENTAREAAUTOHIDE2          1042
#define IDC_USEPERPROTO2                1042
#define IDC_OVERRIDEPERSTATUSCOLOR      1042
#define IDC_EVENTAREASUNKEN             1043
#define IDC_USEPERPROTO3                1043
#define IDC_SETALLBUTTONSKINNED         1043
#define IDC_EVENTSONTOP                 1044
#define IDC_FASTGRADIENT                1044
#define IDC_EXTRAMAIL                   1045
#define IDC_DONTSEPARATE                1045
#define IDC_REASON                      1046
#define IDC_EXTRAPHONE                  1047
#define IDC_EMAIL                       1048
#define IDC_NAMENICK                    1049
#define IDC_NAMEFIRST                   1050
#define IDC_NAMELAST                    1051
#define IDC_EXTRAPHONE2                 1052
#define IDC_NICK                        1053
#define IDC_EXTRARESERVED               1054
#define IDC_EXTRAWEB                    1055
#define IDC_FADEINOUT                   1056
#define IDC_FILENAMES                   1057
#define IDC_EXTRARESERVED2              1057
#define IDC_FONTID                      1058
#define IDC_EXTRARESERVED3              1058
#define IDC_FONTSIZE                    1059
#define IDC_EXTRARESERVED4              1059
#define IDC_GENDER                      1060
#define IDC_EXTRARESERVED5              1060
#define IDC_EXTRAORDER                  1061
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_FRAMEGAP                    1064
#define IDC_FRAMEGAPSPIN                1065
#define IDC_FROM                        1066
#define IDC_CLIPBORDER                  1066
#define IDC_FULLROWSELECT               1067
#define IDC_CLIPBORDERSPIN              1067
#define IDC_LOCALTIME                   1068
#define IDC_EXICONSCALE                 1068
#define IDC_GENMENU_DEFAULT             1069
#define IDC_EXICONSCALESPIN             1069
#define IDC_GENMENU_SET2                1070
#define IDC_CLEFT                       1070
#define IDC_GPLBTN                      1071
#define IDC_CLEFTSPIN                   1071
#define IDC_GREYOUT                     1072
#define IDC_CTOP                        1072
#define IDC_MIN2TRAY                    1073
#define IDC_ONTOP                       1074
#define IDC_SHOWMAINMENU                1075
#define IDC_CLIENTDRAG                  1076
#define IDC_HIDEEMPTYGROUPS             1077
#define IDC_CTOPSPIN                    1077
#define IDC_EDIT                        1078
#define IDC_CBOTTOM                     1078
#define IDC_LIST                        1079
#define IDC_CBOTTOMSPIN                 1079
#define IDC_HISTORY                     1080
#define IDC_CRIGHT                      1080
#define IDC_HIDEOFFLINE                 1081
#define IDC_CLIPBORDERSPIN2             1081
#define IDC_CRIGHTSPIN                  1081
#define IDC_HIDEOFFLINEOPTS             1082
#define IDC_HKREADMSG                   1083
#define IDC_HKSEARCH                    1084
#define IDC_USESOUND                    1085
#define IDC_HKSHOWOPTIONS               1086
#define IDC_LANGUAGE1                   1088
#define IDC_LANGUAGE2                   1089
#define IDC_LANGUAGE3                   1090
#define IDC_LASTNAME                    1091
#define IDC_LEFTMARGINSPIN              1092
#define IDC_MAIL                        1093
#define IDC_MAXSIZESPIN2                1094
#define IDC_MESSAGE                     1095
#define IDC_MOREOPTIONS                 1096
#define IDC_MSG                         1098
#define IDC_NAME                        1099
#define IDC_NATIME                      1100
#define IDC_NETSEARCH                   1101
#define IDC_NOGROUPICON                 1102
#define IDC_NONEICON                    1103
#define IDC_NOTOALL                     1104
#define IDC_ONECLK                      1105
#define IDC_SEARCHURL                   1106
#define IDC_PAGETREE                    1107
#define IDC_BUILDTIME                   1108
#define IDC_PHONE                       1109
#define IDC_PHONES                      1110
#define IDC_PORTSRANGEO                 1111
#define IDC_POSITION                    1112
#define IDC_NUMBER                      1113
#define IDC_PREVIEW                     1114
#define IDC_PROXYAUTH                   1115
#define IDC_PROXYDNS                    1116
#define IDC_PROXYTYPE                   1117
#define IDC_RADIUSSPIN2                 1118
#define IDC_READMSG                     1119
#define IDC_RENDERGDIP                  1120
#define IDC_RIGHTMARGIN                 1121
#define IDC_ROWGAP                      1122
#define IDC_UIN                         1123
#define IDC_TRANSPARENT                 1124
#define IDC_ROWHEIGHT                   1125
#define IDC_TRANSINACTIVE               1126
#define IDC_GROUPROWHEIGHT              1126
#define IDC_RUNNOW                      1127
#define IDC_TRANSACTIVE                 1128
#define IDC_SAMETYPE                    1129
#define IDC_SAMPLE                      1130
#define IDC_FINDWHAT                    1131
#define IDC_FIND                        1132
#define IDC_FILE                        1133
#define IDC_PROFILELIST                 1134
#define IDC_NEWPROFILE                  1135
#define IDC_NEWPROFILENAME              1136
#define IDC_SCANCMDLINEBROWSE           1137
#define IDC_SCRIPT                      1138
#define IDC_SEARCHNEWWND                1139
#define IDC_SELBLEND                    1140
#define IDC_TABS                        1141
#define IDC_RESULTS                     1142
#define IDC_SETNA                       1143
#define IDC_STATUS                      1144
#define IDC_SCREENSAVE                  1145
#define IDC_TIMED                       1146
#define IDC_AWAYTIME                    1147
#define IDC_SHOWBOTTOMBUTTONS           1148
#define IDC_SHOWBUTTONS                 1149
#define IDC_PROXYHOST                   1150
#define IDC_PROXYPORT                   1151
#define IDC_PROXYUSER                   1152
#define IDC_PROXYPASS                   1153
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_STATIC21                    1156
#define IDC_STATIC13                    1156
#define IDC_STATIC22                    1157
#define IDC_STATIC14                    1157
#define IDC_STATIC15                    1158
#define IDC_STATIC31                    1158
#define IDC_STATIC32                    1159
#define IDC_PROXYAUTHNTLM               1160
#define IDC_HKSHOWHIDE                  1162
#define IDC_SHOWCAPTION2                1163
#define IDC_SHOWCLIENTICONS             1164
#define IDC_SHOWCONSOLEATSTART          1165
#define IDC_SHOWEXTENDEDSTATUS          1166
#define IDC_PLUGINLIST                  1167
#define IDC_FEATURENAME                 1168
#define IDC_SHOWGRIP                    1169
#define IDC_SHOWHIDE                    1170
#define IDC_SKINBACKGROUND              1170
#define IDC_FILLWALLPAPER               1171
#define IDC_SHOWMETA                    1172
#define IDC_CENTERGROUPNAMES            1173
#define IDC_SHOWOPTIONS                 1174
#define IDC_CENTERGROUPNAMES2           1174
#define IDC_APPLYINDENTBG               1174
#define IDC_ABOUTGROUP                  1175
#define IDC_DESCRIPTION                 1176
#define IDC_AUTHOR                      1177
#define IDC_COPYRIGHT                   1178
#define IDC_VERSION                     1179
#define IDC_SHOWSTATUSICONS             1180
#define IDC_HOMEPAGE                    1181
#define IDC_SHOWSTATUSICONS2            1181
#define IDC_REVERSEFORRTL               1181
#define IDC_RESTARTREQD                 1182
#define IDC_ICONSET                     1183
#define IDC_BROWSE                      1184
#define IDC_RUNATSTARTBROWSE            1185
#define IDC_SHOWSTATUSMG                1186
#define IDC_INACTIVEPERC                1187
#define IDC_SHOWSTATUSMSG               1188
#define IDC_SHOWTOPBUTTONS              1189
#define IDC_SHOWLOCALTIME               1189
#define IDC_SHOWVISIBILITY              1190
#define IDC_SHOWLOCALTIMEONLYWHENDIFFERENT 1191
#define IDC_RETRIEVING                  1193
#define IDC_SOUNDLIST                   1194
#define IDC_SPECIFYPORTS                1195
#define IDC_TITLETEXT                   1196
#define IDC_SPECIFYPORTSO               1197
#define IDC_ST_ENTERMSG                 1198
#define IDC_ST_ENTERURL                 1199
#define IDC_GETMORE                     1200
#define IDC_STATIC53                    1201
#define IDC_STREET                      1202
#define IDC_SUNKENCLIST                 1203
#define IDC_VISIBLEICON                 1204
#define IDC_INVISIBLEICON               1205
#define IDC_FILEICON                    1206
#define IDC_ONLINEICON                  1207
#define IDC_TILEH                       1208
#define IDC_TIMEZONE                    1209
#define IDC_USEPREVIOUS                 1210
#define IDC_NODIALOG                    1211
#define IDC_USESPECIFIC                 1212
#define IDC_FILEDIR                     1213
#define IDC_TO                          1214
#define IDC_TOCONSOLE                   1215
#define IDC_USEPROXY                    1216
#define IDC_ALLFILESPROGRESS            1217
#define IDC_USERMENU                    1218
#define IDC_CURRENTSPEED                1219
#define IDC_STAWAYTYPE                  1220
#define IDC_WEBPAGE                     1221
#define IDC_CURRENTFILEPROGRESS         1222
#define IDC_CURRENTFILEGROUP            1223
#define IDC_FIRSTNAME                   1224
#define IDC_WHITERECT                   1225
#define IDC_DOBDAY                      1226
#define IDC_DOBMONTH                    1227
#define IDC_ZIP                         1228
#define IDC_UPDATING                    1231
#define IDC_NAMEORDER                   1234
#define IDC_AUTOHIDE                    1235
#define IDC_HIDETIME                    1236
#define IDC_RECONNECTREQD               1239
#define IDC_IMPORT                      1241
#define IDC_TOMAIN                      1243
#define IDC_TOPROTO                     1244
#define IDC_PROTOLIST                   1245
#define IDC_TODEFICON                   1246
#define IDC_IMPORTMULTI                 1247
#define IDC_MAXSIZEHEIGHT               1254
#define IDC_MAXSIZESPIN                 1255
#define IDC_SAMESTYLE                   1258
#define IDC_SAMECOLOUR                  1259
#define IDC_SAMEAS                      1260
#define IDC_TYPEFACE                    1261
#define IDC_BOLD                        1262
#define IDC_ITALIC                      1263
#define IDC_COLOUR                      1264
#define IDC_UNDERLINE                   1265
#define IDC_HOTCOLOUR                   1267
#define IDC_SAMESIZE                    1268
#define IDC_BKGCOLOUR                   1269
#define IDC_FILENAME                    1271
#define IDC_SCROLL                      1277
#define IDC_PROPORTIONAL                1278
#define IDC_SELCOLOUR                   1281
#define IDC_QUICKCOLOUR                 1282
#define IDC_SMOOTHTIME                  1283
#define IDC_SMOOTHTIMESPIN              1284
#define IDC_ROWHEIGHTSPIN               1286
#define IDC_GROUPROWHEIGHTSPIN          1287
#define IDC_GREYOUTOPTS                 1288
#define IDC_GROUPINDENT                 1289
#define IDC_GROUPINDENTSPIN             1290
#define IDC_LEFTMARGIN                  1291
#define IDC_RIGHTMARGINSPIN             1294
#define IDC_RIGHTMARGINSPIN2            1295
#define IDC_ROWGAPSPIN                  1295
#define IDC_STRETCHH                    1298
#define IDC_STRETCHV                    1299
#define IDC_TILEV                       1301
#define IDC_GAMMACORRECT                1302
#define IDC_INTERESTS                   1305
#define IDC_EMAILS                      1306
#define IDC_PAST                        1307
#define IDC_SMS                         1310
#define IDC_AREA                        1312
#define IDC_UPDATE                      1313
#define IDC_DONTCYCLE                   1315
#define IDC_PRIMARYSTATUS               1316
#define IDC_CYCLE                       1317
#define IDC_CYCLETIME                   1318
#define IDC_CYCLETIMESPIN               1319
#define IDC_HIDETIMESPIN                1320
#define IDC_MULTITRAY                   1321
#define IDC_ALWAYSMULTI                 1322
#define IDC_SHOWICON                    1323
#define IDC_SORTTHEN                    1323
#define IDC_SHOWPROTO                   1324
#define IDC_SORTFINALLY                 1324
#define IDC_SHOWSTATUS                  1325
#define IDC_EQUALSECTIONS               1326
#define IDC_SHOWSBAR                    1329
#define IDC_RIGHTMIRANDA                1330
#define IDC_RIGHTSTATUS                 1331
#define IDC_ININAME                     1333
#define IDC_VIEWINI                     1334
#define IDC_SECURITYINFO                1335
#define IDC_SETTINGNAME                 1336
#define IDC_NEWVALUE                    1337
#define IDC_WARNNOMORE                  1338
#define IDC_DELETE                      1339
#define IDC_RECYCLE                     1340
#define IDC_NEWNAME                     1341
#define IDC_MOVE                        1342
#define IDC_LEAVE                       1343
#define IDC_EXPERT                      1346
#define IDC_STAUTOHIDESECS              1349
#define IDC_STCLISTGROUP                1350
#define IDC_DISABLEDRAGDROP             1351
#define IDC_NOTEDITLABELS               1352
#define IDC_SHOWSELALWAYS               1353
#define IDC_TRACKSELECT                 1354
#define IDC_SHOWGROUPCOUNTS             1355
#define IDC_HIDECOUNTSWHENEMPTY         1356
#define IDC_DIVIDERONOFF                1357
#define IDC_NOTNOTRANSLUCENTSEL         1358
#define IDC_LINEWITHGROUPS              1359
#define IDC_QUICKSEARCHVISONLY          1360
#define IDC_SORTGROUPSALPHA             1361
#define IDC_NOTNOSMOOTHSCROLLING        1362
#define IDC_BITMAP                      1363
#define IDC_STWINDOWGROUP               1364
#define IDC_STATIC01                    1365
#define IDC_CATEGORYLIST                1366
#define IDC_LOADICONS                   1369
#define IDC_STICONSGROUP                1371
#define IDC_MSGICON                     1375
#define IDC_URLICON                     1376
#define IDC_STNOPAGE                    1377
#define IDC_STCHECKMARKS                1380
#define IDC_STSAMETEXT                  1382
#define IDC_STASTEXT                    1383
#define IDC_STSIZETEXT                  1384
#define IDC_STCOLOURTEXT                1385
#define IDC_STHORZBAR                   1386
#define IDC_MIRANDA                     1388
#define IDC_STATUSBAR                   1389
#define IDC_PROTOIDGROUP                1392
#define IDC_BYPROTOID                   1393
#define IDC_PROTOID                     1394
#define IDC_EMAILGROUP                  1395
#define IDC_BYEMAIL                     1396
#define IDC_STNAMENICK                  1397
#define IDC_NAMEGROUP                   1398
#define IDC_BYNAME                      1399
#define IDC_STNAMEFIRST                 1400
#define IDC_STNAMELAST                  1401
#define IDC_ADVANCEDGROUP               1402
#define IDC_BYADVANCED                  1403
#define IDC_ADVANCED                    1404
#define IDC_SORTPRIMARY                 1420
#define IDC_STSIMPLERIGHT               1440
#define IDC_NETLIBUSERS                 1443
#define IDC_STOFTENPORT                 1445
#define IDC_STATIC51                    1446
#define IDC_STATIC52                    1447
#define IDC_STATIC43                    1448
#define IDC_LOGOPTIONS                  1449
#define IDC_PORTSRANGE                  1450
#define IDC_STATIC54                    1453
#define IDC_SHOWCONSOLE                 1454
#define IDC_TOOUTPUTDEBUGSTRING         1455
#define IDC_TOFILE                      1456
#define IDC_CLEARCONSOLE                1457
#define IDC_RUNATSTART                  1458
#define IDC_DUMPSENT                    1464
#define IDC_DUMPPROXY                   1466
#define IDC_TEXTDUMPS                   1467
#define IDC_AUTODETECTTEXT              1468
#define IDC_TIMEFORMAT                  1469
#define IDC_FILENAMEBROWSE              1470
#define IDC_SHOWTHISDLGATSTART          1471
#define IDC_FILEDIRBROWSE               1475
#define IDC_ALLTRANSFERRED              1477
#define IDC_OPENFOLDER                  1478
#define IDC_OPENFILE                    1479
#define IDC_TOTALSIZE                   1480
#define IDC_APPENDNICKTODIR             1483
#define IDC_AUTOACCEPT                  1484
#define IDC_SCANCMDLINE                 1485
#define IDC_WARNBEFOREOPENING           1488
#define IDC_SCANDURINGDL                1489
#define IDC_SCANAFTERDL                 1490
#define IDC_NOSCANNER                   1491
#define IDC_ST_CMDLINE                  1492
#define IDC_ST_CMDLINEHELP              1493
#define IDC_PROPERTIES                  1496
#define IDC_RESUME                      1497
#define IDC_EXISTINGICON                1499
#define IDC_RESUMEALL                   1500
#define IDC_OVERWRITE                   1501
#define IDC_OVERWRITEALL                1502
#define IDC_SKIP                        1503
#define IDC_EXISTINGSIZE                1506
#define IDC_EXISTINGDATE                1507
#define IDC_EXISTINGTYPE                1508
#define IDC_NEWICON                     1509
#define IDC_NEWSIZE                     1510
#define IDC_NEWDATE                     1511
#define IDC_NEWTYPE                     1512
#define IDC_SAVEAS                      1513
#define IDC_ASK                         1516
#define IDC_RENAME                      1519
#define IDC_VIRUSSCANNERGROUP           1520
#define IDC_HIDE                        1534
#define IDC_TOPLINE                     1535
#define IDC_MYHANDLE                    1540
#define IDC_GROUP                       1541
#define IDC_ADDED                       1542
#define IDC_AUTH                        1543
#define IDC_PLUGINSTATIC1               1559
#define IDC_DELETEHISTORY               1560
#define IDC_HOTKEYURLSTR                1567
#define IDC_SETNASTR                    1568
#define IDC_AAUTHOR                     1569
#define IDC_AHOMEPAGE                   1570
#define IDC_AVERSION                    1571
#define IDC_ACOPYRIGHT                  1572
#define IDC_ADESCRIPTION                1573
#define IDC_PLUGINENABLE                1574
#define IDC_AUTHREQ                     1577
#define IDC_AUTHGB                      1578
#define IDC_BRINGTOFRONT                1579
#define IDC_PROTOCOL                    1580
#define IDC_CONTRIBLINK                 1586
#define IDC_HOMELINK                    1587
#define IDC_SUPPORTLINK                 1588
#define IDC_DEVS                        1589
#define IDC_GPL                         1590
#define IDC_LOGO                        1591
#define IDC_PROTOCOLORDER               1591
#define IDC_PROTOCOLORDERWARNING        1592
#define IDC_CREDITSTEXT                 1595
#define IDC_WSLOCK                      1599
#define IDC_BLINKTIME                   1607
#define IDC_BLINKSPIN                   1608
#define IDC_DISABLEBLINK                1609
#define IDC_IDLE                        1610
#define IDC_SBPANELBEVEL                1611
#define IDC_DBLCLKAVATARS               1611
#define IDC_IDLE2                       1611
#define IDC_XSTATUSASSTATUS             1611
#define IDC_NOSCROLLBAR                 1613
#define IDC_BUTTON1                     1633
#define IDC_ADDVIEWMODE                 1633
#define IDC_SKINFILESELECT              1633
#define IDC_IGN_ALL                     1633
#define IDC_EXPORT                      1634
#define IDC_DELETEVIEWMODE              1634
#define IDC_IGN_NONE                    1634
#define IDC_RELOAD                      1635
#define IDC_IGN_NONE2                   1635
#define IDC_IGN_ADDPERMANENTLY          1635
#define IDC_IDLECHECK                   1636
#define IDC_DSP_LOADDEFAULT             1636
#define IDC_IDLEONWINDOWS               1637
#define IDC_IDLEONMIRANDA               1638
#define IDC_IDLEUSEGLI                  1639
#define IDC_SCREENSAVER                 1642
#define IDC_LOCKED                      1643
#define IDC_IDLESHORT                   1644
#define IDC_IDLELONG                    1645
#define IDC_IDLE1STTIME                 1646
#define IDC_IDLE2NDTIME                 1647
#define IDC_IDLEPRIVATE                 1649
#define IDC_AASTATUS                    1650
#define IDC_AASHORTIDLE                 1651
#define IDC_AALONGSTATUS                1652
#define IDC_AALONGIDLE                  1656
#define IDC_ONDESKTOP                   1657
#define IDC_WINCOLOUR                   1659
#define IDC_ICONBLINK                   1660
#define IDC_SELECT_D                    1661
#define IDC_ICONBLINK2                  1661
#define IDC_APPLYLASTVIEWMODE           1661
#define IDC_SELECT_F                    1662
#define IDC_SELECT_L                    1663
#define IDC_SELECT_N                    1664
#define IDC_MRGN_BOTTOM                 1670
#define IDC_MRGN_LEFT                   1671
#define IDC_ALPHASPIN                   1682
#define IDC_ITEMS                       1688
#define IDC_CORNER                      1689
#define IDC_MRGN_TOP_SPIN               1693
#define IDC_MRGN_RIGHT_SPIN             1694
#define IDC_MRGN_BOTTOM_SPIN            1695
#define IDC_MRGN_LEFT_SPIN              1696
#define IDC_GRADIENT                    1699
#define IDC_GRADIENT_LR                 1700
#define IDC_GRADIENT_RL                 1701
#define IDC_GRADIENT_TB                 1702
#define IDC_BASECOLOUR                  1703
#define IDC_ALPHA                       1704
#define IDC_MRGN_TOP                    1705
#define IDC_MRGN_RIGHT                  1706
#define IDC_GRADIENT_BT                 1707
#define IDC_BASECOLOUR2                 1708
#define IDC_TEXTCOLOUR                  1709
#define IDC_CORNER_TL                   1710
#define IDC_CORNER_TR                   1711
#define IDC_CORNER_BR                   1712
#define IDC_CORNER_BL                   1713
#define IDC_COLORLABLE                  1714
#define IDC_MARGINLABLE                 1715
#define IDC_ALPHALABLE                  1716
#define IDC_IGNORE                      1717
#define IDC_COLOR2LABLE                 1718
#define IDC_COLOR2_TRANSPARENT          1719
#define IDC_TEXTCOLOURLABLE             1720
#define IDC_IGNORESELFORGROUPS          1722
#define IDC_CLISTAVATARS                1729
#define IDC_ALIGNMENT                   1730
#define IDC_AVATARSBORDER               1732
#define IDC_AVATARBORDERCLR             1733
#define IDC_AVATARSROUNDED              1734
#define IDC_DUALROWMODE                 1735
#define IDC_SHOWBUTTONBAR               1736
#define IDC_ALIGNMENT2                  1737
#define IDC_CLISTALIGN                  1737
#define IDC_CLISTSUNKEN                 1738
#define IDC_EVENTAREAAUTOHIDE           1740
#define IDC_RADIUS                      1742
#define IDC_RADIUSSPIN                  1743
#define IDC_ALWAYSALIGNNICK             1744
#define IDC_SELECTIVEICONS              1746
#define IDC_OVERLAYICONS                1747
#define IDC_AVATARHEIGHT                1748
#define IDC_SELECTIVEICONS2             1749
#define IDC_NOAVATARSOFFLINE            1749
#define IDC_CORNERRAD                   1751
#define IDC_CORNERSPIN                  1752
#define IDC_AVATARPADDING               1753
#define IDC_GRPTOPPADDING               1753
#define IDC_AVATARPADDINGSPIN           1754
#define IDC_GRPPADDINGSPIN              1754
#define IDC_LASTITEMPADDING             1755
#define IDC_LASTITEMPADDINGSPIN         1756
#define IDC_TBHIDEOFFLINE               1800
#define IDC_TBHIDEGROUPS                1801
#define IDC_TBSOUND                     1802
#define IDC_TBFINDANDADD                1803
#define IDC_TBOPTIONS                   1804
#define IDC_TBMINIMIZE                  1805
#define IDC_TBMENU                      1806
#define IDC_TBGLOBALSTATUS              1807
#define IDC_TABSRMMSLIST                1808
#define IDC_TABSRMMMENU                 1809
#define IDC_TBSELECTVIEWMODE            1810
#define IDC_ROUNDEDBORDER               1810
#define IDC_TBCLEARVIEWMODE             1811
#define IDC_TBCONFIGUREVIEWMODE         1812
#define IDC_TBTOPMENU                   1813
#define IDC_TBTOPSTATUS                 1814
#define IDC_TBFIRSTUID                  1820
#define IDC_NOTIFYBUTTON                1900
#define IDC_CLNICER                     2002
#define IDC_SUPPORT                     2003
#define IDI_OVL_OFFLINE                 2050
#define IDI_OVL_ONLINE                  2051
#define IDI_OVL_AWAY                    2052
#define IDI_OVL_DND                     2053
#define IDI_OVL_NA                      2054
#define IDI_OVL_OCCUPIED                2055
#define IDI_OVL_FREEFORCHAT             2056
#define IDI_OVL_INVISIBLE               2057
#define IDI_OVL_ONTHEPHONE              2058
#define IDI_OVL_OUTTOLUNCH              2059
#define IDI_HIDEOFFLINE                 2100
#define IDI_HIDEGROUPS                  2101
#define IDI_SOUNDSON                    2102
#define IDI_FINDANDADD                  2103
#define IDI_TBOPTIONS                   2104
#define IDI_MINIMIZE                    2105
#define IDI_SOUNDSOFF                   2106
#define IDI_TABSRMMSESSIONLIST          2107
#define IDI_TABSRMMMENU                 2108
#define IDI_CLVISIBLE                   2109
#define IDI_CLINVISIBLE                 2110
#define IDI_PROTOCONNECTING             2111
#define IDI_TBTOPMENU                   2112
#define IDI_PUMPKIN                     3000
#define IDC_MENUITEMS                   11710
#define IDC_MENUOBJECTS                 11711
#define IDC_NOTSUPPORTWARNING           11712
#define IDC_INSERTSEPARATOR             11715
#define IDC_GENMENU_SERVICE             11716
#define IDC_GENMENU_CUSTOMNAME          11717
#define IDC_GENMENU_SET                 11718
#define IDC_CLUIFRAMESBDR               25492
#define IDC_FLT_PADLEFTSPIN             25494
#define IDC_FLT_PADLEFT                 25495
#define IDC_GROUPALIGN                  25499
#define IDC_BORDERSTYLE                 25501
#define IDC_CURVIEWMODE2                25503
#define IDC_3DDARKCOLOR                 25504
#define IDC_3DLIGHTCOLOR                25505
#define IDI_SEARCHALL                   32548
#define ID_ICQ_EXIT                     40001
#define ID_RESET                        40002
#define IDC_STATIC7                     40002
#define POPUP_HIDEEMPTYGROUPS           40003
#define POPUP_NEWSUBGROUP               40004
#define POPUP_HIDEOFFLINE               40005
#define POPUP_GROUPHIDEOFFLINE          40006
#define POPUP_HIDEOFFLINEROOT           40007
#define POPUP_DISABLEGROUPS             40008
#define IDC_SENDMESSAGE                 40009
#define IDC_VIEWMODES                   40010
#define IDC_PROTOCOLS                   40011
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDC_GROUPS                      40012
#define IDM_CLEAR                       40013
#define IDC_STATUSMODES                 40013
#define IDM_OPENNEW                     40014
#define IDC_NEWVIEMODE                  40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define POPUP_HIDEMIRANDA               40017
#define IDC_TAB                         40017
#define IDC_STATIC1                     40018
#define IDC_STATIC2                     40019
#define IDC_STATIC3                     40020
#define POPUP_VISIBILITY                40021
#define IDC_STATIC16                    40021
#define IDC_STATIC4                     40022
#define IDC_STATIC5                     40023
#define IDC_STATIC6                     40024
#define IDC_CLIST                       40025
#define IDC_STATIC8                     40026
#define POPUP_TOOLBAR                   40027
#define IDC_STATIC9                     40027
#define POPUP_BUTTONS                   40028
#define IDC_CLEARALL                    40028
#define POPUP_FRAME                     40029
#define IDC_STATIC10                    40029
#define IDC_PROTOGROUPOP                40030
#define POPUP_MOVEMARKEDHERE            40031
#define IDC_GROUPSTATUSOP               40031
#define ID_BUTTONBAR_BUTTONS            40032
#define IDC_LASTMESSAGEOP               40032
#define ID_BUTTONS_ONLINE               40033
#define ID_BUTTONBAR_INCREASEBUTTONSIZE 40034
#define IDC_SKINFILE                    40034
#define IDC_LASTMESSAGEOP2              40034
#define IDC_LASTMESSAGEUNIT             40034
#define ID_BUTTONBAR_DECREASEBUTTONSIZE 40035
#define ID_BUTTONBAR_FLATBUTTONS        40036
#define IDC_CHECK2                      40036
#define IDC_GROUPAUTOEXPAND             40036
#define IDC_FLT_AVATARS                 40036
#define IDC_HIDECONTACT                 40036
#define ID_BUTTONBAR_NOVISUALSTYLES     40037
#define IDC_FLT_DUALROWS                40037
#define ID_TRAY_HIDE                    40038
#define IDC_FLT_EXTRAICONS              40038
#define ID_TRAY_EXIT                    40039
#define IDC_FLT_SYNCED                  40039
#define POPUP_SHOWMETAICONS             40040
#define IDC_FLT_AUTOHIDE                40040
#define ID_NOWHERE_APPEARANCE           40041
#define ID_APPEARANCE_BLA               40042
#define ID_NOWHERE_EVENTAREA            40043
#define IDC_FLT_PADRIGHT                40043
#define IDC_LASTMSGVALUE                40043
#define IDC_FLT_PADRIGHTSPIN            40044
#define IDC_FLT_PADTOP                  40045
#define IDC_SKINFILENAME                40045
#define IDC_FLT_PADTOPSPIN              40046
#define IDC_SELECTSKINFILE              40046
#define POPUP_ADJUSTSIZE                40047
#define IDC_FLT_PADBOTTOM               40047
#define IDC_RELOADSKIN                  40047
#define IDC_FLT_PADBOTTOMSPIN           40048
#define IDC_UNLOAD                      40048
#define ID_BUTTONBAR_DRAWSUNKENFRAME    40049
#define POPUP_NEWGROUP                  40050
#define IDC_SECONDLINEMODE              40050
#define POPUP_SHOWSTATUSICONS           40051
#define IDC_OVERLAYICON                 40051
#define IDC_SHOWLOCALTIME1              40052
#define POPUP_RENAMEGROUP               40052
#define POPUP_DELETEGROUP               40053
#define IDC_SHOWLOCALTIME2              40053
#define IDC_DSP_ADD                     -25483
#define ID_BUTTONBAR_SKINNEDTOOLBAR     40054
#define IDC_DSP_DELETE                  40054
#define ID_APPEARANCE_USESTATUSFLOATER  40055
#define IDC_DSP_RENAME                  40055
#define ID_APPEARANCE_AUTO              40056
#define IDC_DSP_APPLY                   40056
#define POPUP_FLOATER                   40057
#define POPUP_FLOATER_AUTOHIDE          40058
#define IDC_AVATARDISPMODE              40059
#define ID_APPEARANCE_SHOWEVENTAREAINFLOATER 40059
#define POPUP_FLOATER_EVENTS            40060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         40054
#define _APS_NEXT_SYMED_VALUE           40154
#endif
#endif
