# Project: tabsrmm
# Makefile created by Dev-C++ 4.9.9.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
LIBDIR=c:/mingw/lib
RES  = tabsrmm_private.res
OBJ  = Release_MINGW32_UNICODE/manager.o Release_MINGW32_UNICODE/message.o Release_MINGW32_UNICODE/options.o  \
       Release_MINGW32_UNICODE/services.o Release_MINGW32_UNICODE/tools.o \
       Release_MINGW32_UNICODE/main.o Release_MINGW32_UNICODE/colorchooser.o Release_MINGW32_UNICODE/clist.o \
       Release_MINGW32_UNICODE/log.o Release_MINGW32_UNICODE/window.o Release_MINGW32_UNICODE/tsbutton.o \
       Release_MINGW32_UNICODE/tabctrl.o Release_MINGW32_UNICODE/userprefs.o Release_MINGW32_UNICODE/templates.o \
       Release_MINGW32_UNICODE/eventpopups.o Release_MINGW32_UNICODE/trayicon.o Release_MINGW32_UNICODE/formatting.o \
       Release_MINGW32_UNICODE/ImageDataObject.o Release_MINGW32_UNICODE/themes.o Release_MINGW32_UNICODE/sendqueue.o \
       Release_MINGW32_UNICODE/msgdlgutils.o Release_MINGW32_UNICODE/container.o Release_MINGW32_UNICODE/containeroptions.o \
       Release_MINGW32_UNICODE/hotkeyhandler.o Release_MINGW32_UNICODE/msgdialog.o Release_MINGW32_UNICODE/msglog.o \
       Release_MINGW32_UNICODE/msgoptions.o Release_MINGW32_UNICODE/msgs.o Release_MINGW32_UNICODE/selectcontainer.o \
       Release_MINGW32_UNICODE/generic_msghandlers.o \
       Release_MINGW32_UNICODE/srmm.o $(RES)

LINKOBJ  = $(OBJ)

LIBS =  -L"C:/mingw/lib" --no-export-all-symbols --add-stdcall-alias $(LIBDIR)/libmsimg32.a $(LIBDIR)/libshlwapi.a $(LIBDIR)/libgdi32.a $(LIBDIR)/libole32.a $(LIBDIR)/libuser32.a $(LIBDIR)/libcomctl32.a $(LIBDIR)/libuuid.a $(LIBDIR)/libcomdlg32.a $(LIBDIR)/libstdc++.a -mwindows -s
INCS =  -I"C:/mingw/include"
CXXINCS =  -I"C:/mingw/include"
BIN  = ../../bin/release/plugins/tabsrmm_unicode.dll
CXXFLAGS = $(INCS) -DBUILDING_DLL=1  -D__GNUWIN32__ -DUNICODE -DNDEBUG -Os -mwindows -fno-exceptions -fomit-frame-pointer -fmerge-all-constants -fno-rtti
CFLAGS = $(INCS) -DBUILDING_DLL=1 -D__GNUWIN32__ -DUNICODE -DNDEBUG -fno-exceptions -fmerge-all-constants -fomit-frame-pointer -Os -mwindows

.PHONY: all all-before all-after clean clean-custom

all: ../../bin/release/plugins/tabsrmm_unicode.dll


clean:
	rm -f $(OBJ) $(BIN)

DLLWRAP=dllwrap.exe
DEFFILE=Release_MINGW32_UNICODE/libtabsrmm.def
STATICLIB=Release_MINGW32_UNICODE/libtabsrmm.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

Release_MINGW32_UNICODE/window.o: chat/window.c
	$(CC) -c chat/window.c -o Release_MINGW32_UNICODE/window.o $(CFLAGS)

Release_MINGW32_UNICODE/log.o: chat/log.c
	$(CC) -c chat/log.c -o Release_MINGW32_UNICODE/log.o $(CFLAGS)

Release_MINGW32_UNICODE/clist.o: chat/clist.c
	$(CC) -c chat/clist.c -o Release_MINGW32_UNICODE/clist.o $(CFLAGS)

Release_MINGW32_UNICODE/colorchooser.o: chat/colorchooser.c
	$(CC) -c chat/colorchooser.c -o Release_MINGW32_UNICODE/colorchooser.o $(CFLAGS)

Release_MINGW32_UNICODE/main.o: chat/main.c
	$(CC) -c chat/main.c -o Release_MINGW32_UNICODE/main.o $(CFLAGS)

Release_MINGW32_UNICODE/manager.o: chat/manager.c
	$(CC) -c chat/manager.c -o Release_MINGW32_UNICODE/manager.o $(CFLAGS)

Release_MINGW32_UNICODE/message.o: chat/message.c
	$(CC) -c chat/message.c -o Release_MINGW32_UNICODE/message.o $(CFLAGS)

Release_MINGW32_UNICODE/options.o: chat/options.c
	$(CC) -c chat/options.c -o Release_MINGW32_UNICODE/options.o $(CFLAGS)

Release_MINGW32_UNICODE/services.o: chat/services.c
	$(CC) -c chat/services.c -o Release_MINGW32_UNICODE/services.o $(CFLAGS)

Release_MINGW32_UNICODE/tools.o: chat/tools.c
	$(CC) -c chat/tools.c -o Release_MINGW32_UNICODE/tools.o $(CFLAGS)

Release_MINGW32_UNICODE/tsbutton.o: tsbutton.c
	$(CC) -c tsbutton.c -o Release_MINGW32_UNICODE/tsbutton.o $(CFLAGS)

Release_MINGW32_UNICODE/tabctrl.o: tabctrl.c
	$(CC) -c tabctrl.c -o Release_MINGW32_UNICODE/tabctrl.o $(CFLAGS)

Release_MINGW32_UNICODE/userprefs.o: userprefs.c
	$(CC) -c userprefs.c -o Release_MINGW32_UNICODE/userprefs.o $(CFLAGS)

Release_MINGW32_UNICODE/trayicon.o: trayicon.c
	$(CC) -c trayicon.c -o Release_MINGW32_UNICODE/trayicon.o $(CFLAGS)

Release_MINGW32_UNICODE/templates.o: templates.c
	$(CC) -c templates.c -o Release_MINGW32_UNICODE/templates.o $(CFLAGS)

Release_MINGW32_UNICODE/eventpopups.o: eventpopups.c
	$(CC) -c eventpopups.c -o Release_MINGW32_UNICODE/eventpopups.o $(CFLAGS)

Release_MINGW32_UNICODE/ImageDataObject.o: ImageDataObject.cpp
	$(CPP) -c ImageDataObject.cpp -o Release_MINGW32_UNICODE/ImageDataObject.o $(CXXFLAGS)

Release_MINGW32_UNICODE/formatting.o: formatting.cpp
	$(CPP) -c formatting.cpp -o Release_MINGW32_UNICODE/formatting.o $(CXXFLAGS)

Release_MINGW32_UNICODE/themes.o: themes.c
	$(CC) -c themes.c -o Release_MINGW32_UNICODE/themes.o $(CFLAGS)

Release_MINGW32_UNICODE/sendqueue.o: sendqueue.c
	$(CC) -c sendqueue.c -o Release_MINGW32_UNICODE/sendqueue.o $(CFLAGS)

Release_MINGW32_UNICODE/msgdlgutils.o: msgdlgutils.c
	$(CC) -c msgdlgutils.c -o Release_MINGW32_UNICODE/msgdlgutils.o $(CFLAGS)

Release_MINGW32_UNICODE/container.o: container.c
	$(CC) -c container.c -o Release_MINGW32_UNICODE/container.o $(CFLAGS)

Release_MINGW32_UNICODE/containeroptions.o: containeroptions.c
	$(CC) -c containeroptions.c -o Release_MINGW32_UNICODE/containeroptions.o $(CFLAGS)

Release_MINGW32_UNICODE/hotkeyhandler.o: hotkeyhandler.c
	$(CC) -c hotkeyhandler.c -o Release_MINGW32_UNICODE/hotkeyhandler.o $(CFLAGS)

Release_MINGW32_UNICODE/msgdialog.o: msgdialog.c
	$(CC) -c msgdialog.c -o Release_MINGW32_UNICODE/msgdialog.o $(CFLAGS)

Release_MINGW32_UNICODE/msglog.o: msglog.c
	$(CC) -c msglog.c -o Release_MINGW32_UNICODE/msglog.o $(CFLAGS)

Release_MINGW32_UNICODE/msgoptions.o: msgoptions.c
	$(CC) -c msgoptions.c -o Release_MINGW32_UNICODE/msgoptions.o $(CFLAGS)

Release_MINGW32_UNICODE/msgs.o: msgs.c
	$(CC) -c msgs.c -o Release_MINGW32_UNICODE/msgs.o $(CFLAGS)

Release_MINGW32_UNICODE/selectcontainer.o: selectcontainer.c
	$(CC) -c selectcontainer.c -o Release_MINGW32_UNICODE/selectcontainer.o $(CFLAGS)

Release_MINGW32_UNICODE/generic_msghandlers.o: generic_msghandlers.c
	$(CC) -c generic_msghandlers.c -o Release_MINGW32_UNICODE/generic_msghandlers.o $(CFLAGS)

Release_MINGW32_UNICODE/srmm.o: srmm.c
	$(CC) -c srmm.c -o Release_MINGW32_UNICODE/srmm.o $(CFLAGS)

tabsrmm_private.res: tabsrmm_private.rc
	$(WINDRES) -i tabsrmm_private.rc -J rc -o tabsrmm_private.res -O coff -D__GNUWIN32__ -DUNICODE
