//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDC_READNEXT                    3
#define IDC_APPLY                       3
#define IDR_CONTEXT                     180
#define IDC_DROP                        183
#define IDC_HYPERLINKHAND               214
#define IDC_DROPUSER                    215
#define IDD_OPT_MSGDLG                  243
#define IDD_OPT_MSGLOG                  245
#define IDD_OPT_MSGTYPE                 275
#define IDD_MSGCONTAINER                276
#define IDD_OPT_TABBEDMSG               277
#define IDR_ACCEL                       283
#define IDR_TABCONTEXT                  286
#define IDM                             286
#define IDD_SELECTCONTAINER             299
#define IDD_CONTAINEROPTIONS            300
#define IDD_DIALOG1                     301
#define IDD_OPT_CONTAINERS              301
#define IDD_HOTKEYSLAVE                 303
#define IDR_MENUBAR                     308
#define IDC_LOG                         1001
#define IDC_MESSAGE                     1002
#define IDC_AUTOPOPUP                   1003
#define IDC_AUTOCLOSE                   1004
#define IDC_AUTOMIN                     1005
#define IDC_TIME                        1006
#define IDC_MULTIPLE                    1007
#define IDC_QUOTE                       1008
#define IDC_NAME                        1009
#define IDC_CLOSE                       1010
#define IDC_SAVE                        1010
#define IDC_CONTACTPIC                  1012
#define IDC_ST_ENTERMSG                 1013
#define IDC_SPLITTER                    1017
#define IDC_SPLITTER2                   1018
#define IDC_SPLITTER5                   1018
#define IDC_SHOWNAMES                   1024
#define IDC_CLOSEONREPLY                1028
#define IDC_SHOWFILES                   1029
#define IDC_SHOWSENDBTN                 1029
#define IDC_SHOWURLS                    1031
#define IDC_SHOWLOGICONS                1032
#define IDC_SHOWTIMES                   1033
#define IDC_SHOWDATES                   1034
#define IDC_CLIST                       1035
#define IDC_MULTISPLITTER               1036
#define IDC_SAVEPERCONTACT              1037
#define IDC_LOADCOUNTN                  1039
#define IDC_LOADCOUNTSPIN               1040
#define IDC_SHOWINFOLINE                1041
#define IDC_SHOWBUTTONLINE              1042
#define IDC_LOADUNREAD                  1043
#define IDC_SENDONENTER                 1043
#define IDC_LOADCOUNT                   1044
#define IDC_SENDONDBLENTER              1044
#define IDC_LOADTIMEN                   1045
#define IDC_LOADTIMESPIN                1046
#define IDC_LOADTIME                    1047
#define IDC_FONTLIST                    1048
#define IDC_CHOOSEFONT                  1049
#define IDC_STMINSOLD                   1051
#define IDC_DETAILS                     1069
#define IDC_ADD                         1070
#define IDC_USERMENU                    1071
#define IDC_RTL                         1072
#define IDC_PIC                         1073
#define IDC_SMILEYBTN                   1074
#define IDC_HISTORY                     1080
#define IDC_FONTID                      1256
#define IDC_SAMETYPE                    1257
#define IDC_SAMESTYLE                   1258
#define IDC_SAMECOLOUR                  1259
#define IDC_SAMEAS                      1260
#define IDC_TYPEFACE                    1261
#define IDC_BOLD                        1262
#define IDC_ITALIC                      1263
#define IDC_SAMESIZE                    1268
#define IDC_BKGCOLOUR                   1269
#define IDC_INPUTBKG                    1270
#define IDC_MATH_BKGCOLOUR              1271
#define IDC_BKGOUTGOING                 1271
#define IDC_BKGINCOMING                 1272
#define IDC_FONTCOLOUR                  1282
#define IDC_SAMPLE                      1292
#define IDC_FONTSIZE                    1293
#define IDC_COLOUR                      1294
#define IDC_SCRIPT                      1300
#define IDC_STSAMETEXT                  1382
#define IDC_STASTEXT                    1383
#define IDC_STSIZETEXT                  1384
#define IDC_STCOLOURTEXT                1385
#define IDC_PRESETSPLIT                 1441
#define IDC_PRESETSINGLE                1442
#define IDC_STMSGLOGGROUP               1442
#define IDC_PROTOCOL                    1580
#define IDC_TYPING                      1581
#define IDC_TYPINGNOTIFY                1581
#define IDC_ERRORTEXT                   1596
#define IDC_SHOWNOTIFY                  1600
#define IDC_STATUSWIN                   1601
#define IDC_TYPEWIN                     1602
#define IDC_CHARCOUNT                   1603
#define IDC_TYPETRAY                    1603
#define IDC_CASCADE                     1604
#define IDC_SECONDS                     1605
#define IDC_NOTIFYTRAY                  1606
#define IDC_NOTIFYBALLOON               1607
#define IDC_SHOW_EVENTS_NL              1608
#define IDC_MathSubst                   1608
#define IDC_INDENT                      1609
#define IDC_INDENTAMOUNT                1610
#define IDC_MSGTABS                     1611
#define IDC_UNDERLINE                   1613
#define IDC_SHOWSECONDS                 1614
#define IDC_WARNONCLOSE                 1614
#define IDC_CUT_TABTITLE                1615
#define IDC_CUT_TITLEMAX                1616
#define IDC_SHOWTABTIP                  1617
#define IDC_SHOWSTATUSONTAB             1618
#define IDC_SWAPTIMESTAMP               1620
#define IDC_AUTOCREATETABS              1621
#define IDC_LOCALTIME                   1621
#define IDC_O_HIDETITLE                 1621
#define IDC_STICKY                      1621
#define IDC_LOGSTATUS                   1621
#define IDC_DEBUGPOPUPS                 1621
#define IDC_CONTAINERGROUPMODE          1621
#define IDC_SELFTYPING                  1621
#define IDC_LOGHOTKEYS                  1622
#define IDC_NOTITLE                     1623
#define IDC_TABPADDING                  1624
#define IDC_PADSPIN                     1625
#define IDC_SHORTCAPTION                1626
#define IDC_POPUPCONTAINER              1627
#define IDC_CHECK2                      1628
#define IDC_NEWSPLITLAYOUT              1628
#define IDC_O_NOTABS                    1628
#define IDC_DONTREPORTUNFOCUSED         1628
#define IDC_ESC_MINIMIZE                1628
#define IDC_USEDIVIDERS                 1628
#define IDC_DRAWGRID                    1628
#define IDC_LIMITTABS                   1628
#define IDC_AUTOLOCALE                  1629
#define IDC_DONTREPORTUNFOCUSED2        1629
#define IDC_GCHECK                      1630
#define IDC_HIDETAB                     1630
#define IDC_O_DONTREPORT                1630
#define IDC_USEDEFERRED                 1630
#define IDC_AUTOSWITCHTABS              1630
#define IDC_USEINDIVIDUALBKG            1630
#define IDC_SINGLEWINDOWMODE            1630
#define IDC_FLATBUTTONS                 1631
#define IDC_O_STICKY                    1631
#define IDC_DIVIDERSUSEPOPUPCONFIG      1631
#define IDC_INOUTICONS                  1631
#define IDC_FLASHFOREVER                1632
#define IDC_DONTFLASH                   1633
#define IDC_RADIO1                      1634
#define IDC_O_FLASHDEFAULT              1634
#define IDC_FLASHDEFAULT                1634
#define IDC_DEFAULTCONTAINERMODE        1634
#define IDOK1                           1635
#define IDC_FULLUSERNAME                1636
#define IDC_CHECK5                      1637
#define IDC_IGNORECONTACTSETTINGS       1637
#define IDC_TRANSPARENCY                1637
#define IDC_AUTOCREATECONTAINER         1637
#define IDC_LIMITAVATARS                1637
#define IDC_DONTREPORT                  1638
#define IDC_SPIN1                       1639
#define IDC_CNTLIST                     1640
#define IDC_NEWCONTAINER                1641
#define IDC_BUTTON1                     1642
#define IDC_CREATENEW                   1642
#define IDC_LOADDEFAULTS                1642
#define IDC_SENDLATER                   1642
#define IDC_RETRY                       1642
#define IDC_DELETECONTAINER             1643
#define IDC_CANCELSEND                  1643
#define IDC_O_FLASHALWAYS               1644
#define IDC_RENAMECONTAINER             1644
#define IDC_RETRY2                      1644
#define IDC_MSGSENDLATER                1644
#define IDC_O_FLASHNEVER                1645
#define IDC_NEWCONTAINERNAME            1645
#define IDC_O_TITLENEVER                1646
#define IDC_O_TITLEFRONT                1647
#define IDC_O_TITLESUFFIX               1648
#define IDC_TRANSPARENCY_ACTIVE         1651
#define IDC_TRANSPARENCY_INACTIVE       1653
#define IDC_TLABEL_ACTIVE               1654
#define IDC_TLABEL_INACTIVE             1655
#define IDC_APPLYASDEFAULT              1657
#define IDC_SHOWCONTACTNAME             1658
#define IDC_SHOWSTATUS                  1659
#define IDC_APPLYEXISTING               1660
#define IDC_DEFAULTDISPLAYNAME          1661
#define IDC_INDENTSPIN                  1662
#define IDC_TABBORDER                   1663
#define IDC_SPIN2                       1664
#define IDC_TABBORDERSPIN               1664
#define IDC_HIDESBAR                    1665
#define IDC_CLISTMODE                   1666
#define IDC_ALWAYSPOPUPSINACTIVE        1667
#define IDC_HISTORYSIZE                 1668
#define IDC_HISTORYSIZESPIN             1669
#define IDC_HOTKEYSAREGLOBAL            1670
#define IDC_SINGLEROWTAB                1671
#define IDC_COMBO1                      1674
#define IDC_MODIFIERS                   1674
#define IDC_AVATARMODE                  1674
#define IDC_RICHEDIT21                  1676
#define IDC_CHECK6                      1677
#define IDC_EMPTYLINEFIX                1677
#define IDC_SPLITTERSTATICEDGES         1677
#define IDC_STREAMTHREADING             1677
#define IDC_EDIT1                       1678
#define IDC_MAXAVATARHEIGHT             1678
#define IDC_TABLIMIT                    1678
#define IDC_RIGHTINDENT                 1678
#define IDC_AVATARSPIN                  1679
#define IDC_TABLIMITSPIN                1680
#define IDC_AGGRESSIVEUPDATE            1684
#define IDC_THINSEPARATORS              1685
#define IDC_RINDENTSPIN                 1686
#define IDC_STATICERRORICON             1687
#define IDC_STATICTEXT                  1688
#define IDC_GROUPMODE                   1689
#define IDC_CHECK1                      1690
#define IDC_SYNCSOUNDS                  1690
#define IDC_RELATIVEDATES               1690
#define IDC_LONGDATES                   1691
#define IDC_CHECK3                      1692
#define IDC_CNTNOSTATUSBAR              1692
#define IDC_HIDEMENUBAR                 1693
#define IDC_TABSATBOTTOM                1694
#define IDC_STATICCONTROL               1695
#define IDD_MSGSPLITNEW                 2000
#define IDD_OPT_MSGWINDOWFONTS          2001
#define IDM_COPY                        40001
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENNEW                     40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define IDM_STICKY                      40020
#define ID_CLOSETAB_DETACHTAB           40025
#define ID_TABCONTEXT_NEXTTAB           40028
#define ID_TABCONTEXT_ATTACH            40029
#define ID_TABCONTEXT_CLOSECONTAINER    40030
#define ID_TABCONTEXT_PREVTAB           40031
#define ID_CLOSETAB                     40032
#define ID_TABMENU_CLOSETAB             40033
#define ID_TABMENU_SWITCHTONEXTTAB      40034
#define ID_TABMENU_SWITCHTOPREVIOUSTAB  40036
#define ID_TABMENU_SAVELOCALESETTINGFORTHISCONTACT 40037
#define ID_TABMENU_OPENWINDOWSERVICE    40038
#define IDM_REPORTALWAY                 40042
#define IDM_REPORTNEVER                 40043
#define IDM_DONTREPORTMINIMIZED         40044
#define ID_TABMENU_ATTACHTOCONTAINER    40047
#define ID_Menu                         40049
#define ID_PICMENU_ALIGNFORMAXIMUMLOGSIZE 40050
#define ID_PICMENU_ALIGNFORFULL         40051
#define ID_PICMENU_RESETPICTURESETTINGS 40052
#define ID_PICMENU_TOGGLEAVATARDISPLAY  40053
#define ID_LOG_CONTAINEROPTIONS         40054
#define ID_TABMENU_CONTAINEROPTIONS     40055
#define ID_LOGMENU_SHOWTIMESTAMP        40057
#define ID_LOGMENU_INDENTMESSAGEBODY    40058
#define ID_LOGMENU_MESSAGEBODYINANEWLINE 40059
#define ID_LOGMENU_USECONTACTSLOCALTIME 40060
#define ID_LOGMENU_SHOWDATE             40061
#define ID_LOGMENU_SHOWSECONDS          40062
#define ID_LOGMENU_UNDERLINETIMESTAMP   40063
#define ID_LOGMENU_ACTIVATERTL          40064
#define ID_LOGMENU_SHOWNICKNAME         40065
#define ID_LOGMENU_SHOWMESSAGEICONS     40066
#define ID_LOGMENU_LOADDEFAULTS         40067
#define ID_LOGMENU_SAVETHESESETTINGSASDEFAULTVALUES 40068
#define ID_LOGMENU_DISPLAYTIMESTAMPAFTERNICKNAME 40069
#define ID_LOGMENU_ALWAYSUSEGLOBALSPLITTERPOSITION 40070
#define ID_LOGMENU_TIMESTAMPSETTINGS    40071
#define ID_LOGMENU_MESSAGELOGFORMATTING 40073
#define ID_TABMENU_CLOSECONTAINER       40075
#define ID_Menu40076                    40076
#define ID_STATUSBARSETTINGS_USEGLOBALDEFAULT 40077
#define ID_STATUSBARSETTINGS_SHOWTHESTATUSBAR 40078
#define ID_STATUSBARSETTINGS_HIDETHESTATUSBAR 40079
#define ID_MESSAGELOGFORMATTING_SHOWGRID 40081
#define ID_MESSAGELOGFORMATTING_USEINDIVIDUALBACKGROUNDCOLORS 40082
#define ID_PICMENU_                     40083
#define ID_PICMENU_RESETTHEAVATAR       40084
#define ID_PICMENU_LOADALOCALPICTUREASAVATAR 40085
#define ID_MESSAGELOGFORMATTING_GROUPMESSAGES 40086
#define ID_TIMESTAMPSETTINGS_USERELATIVETIMESTAMPS 40087
#define ID_TIMESTAMPSETTINGS_USELONGDATEFORMAT 40088
#define ID_VIEW_SHOWMENUBAR             40091
#define ID_VIEW_SHOWSTATUSBAR           40092
#define ID_VIEW_SHOWTOOLBAR             40093
#define ID_TOOLBAR_SENDBUTTON           40094
#define ID_TOOLBAR_USERINFORMATION      40095
#define ID_TOOLBAR_EXTRABUTTONS         40096
#define ID_VIEW_SHOWAVATAR              40097
#define ID_VIEW_SHOWTITLEBAR            40098
#define ID_FILE                         40099
#define ID_FILE_CLOSE                   40100
#define ID_FILE_CLOSEMESSAGESESSION     40101
#define ID_VIEW_SHOWMULTISENDCONTACTLIST 40102
#define ID_VIEW_TITLEBAR                40103
#define ID_TITLEBAR_SHOWNICNAME         40104
#define ID_TITLEBAR_SHOWSTATUS          40105
#define ID_TITLEBAR_SHOWCONTAINERNAME   40106
#define ID_TITLEBAR_SHOWCONTAINERNAMEASSUFFIX 40107
#define ID_VIEW_TABSATBOTTOM            40108
#define ID_TITLEBAR_DONOTSHOWCONTAINERNAME 40109
#define ID_VIEW_STAYONTOP               40110
#define ID_HELP                         40111
#define ID_OPTIONS_EVENTPOPUPS          40112
#define ID_EVENTPOPUPS_DISABLEALLEVENTPOPUPS 40113
#define ID_OPTIONS_APPLYCONTAINEROPTIONSGLOBALLY 40114
#define ID_OPTIONS_SETCURRENTOPTIONSASDEFAULTVALUES 40115
#define ID_OPTIONS_SOUNDS               40116
#define ID_SOUNDS_DISABLEALLMESSAGESOUNDS 40117
#define ID_SOUNDS_SYNCSOUNDSWITHEVENTPOPUPS 40118
#define ID_SOUNDS_ENABLEALLMESSAGESOUNDS 40119
#define ID_VIEW_FLASHING                40120
#define ID_WINDOWFLASHING_USEDEFAULTVALUES 40121
#define ID_WINDOWFLASHING_FLASHUNTILFOCUSED 40122
#define ID_WINDOWFLASHING_DISABLEFLASHING 40123
#define ID_FILE_SAVEMESSAGELOGAS        40124
#define ID_EVENTPOPUPS_SHOWPOPUPSIFWINDOWISMINIMIZED 40131
#define ID_EVENTPOPUPS_SHOWPOPUPSIFWINDOWISUNFOCUSED 40132
#define ID_EVENTPOPUPS_SHOWPOPUPSFORALLINACTIVESESSIONS 40133
#define ID_OPTIONS_SAVECURRENTWINDOWPOSITIONASDEFAULT 40134
#define ID_CONTAINER_CONTAINEROPTIONS   40135
#define ID_MESSAGELOG                   40136
#define ID_MESSAGELOG_LOGITEMSTOSHOW    40137
#define ID_LOGITEMSTOSHOW_USETHINGRIDLINES 40141
#define ID_MESSAGELOG_TIMESTAMPSETTINGS 40142
#define ID_MESSAGELOG_MESSAGELOGFORMATTING 40148
#define ID_LOGITEMSTOSHOW_LOGSTATUSCHANGES 40155
#define ID_MESSAGELOG_MESSAGELOGSETTINGSAREGLOBAL 40157
#define IDM_CUT                         40162
#define IDM_PASTE                       40163
#define ID_PICMENU_DISABLEAUTOMATICAVATARUPDATES 40165
#define IDM_PASTEFORMATTED              40168
#define ID_MESSAGELOG_APPLYMESSAGELOGSETTINGSTOALLCONTACTS 40169
#define ID_LOGMENU_MESSAGELOGSETTINGSAREGLOBAL 40170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         40173
#define _APS_NEXT_CONTROL_VALUE         1696
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
