#include "m_button.h"

#define BUTTONSETID				WM_USER+55
#define BUTTONDRAWINPARENT		WM_USER+56
#define BUTTONSETMARGINS		WM_USER+57

#define MBM_UPDATETRANSPARENTFLAG	WM_USER+52
#define MBM_SETICOLIBHANDLE			WM_USER+53
#define MBM_REFRESHICOLIBICON		WM_USER+54



#define BUTTONNEEDREDRAW		1256