/*
Change ICQ Details plugin for Miranda IM

Copyright © 2001-2005 Richard Hughes, Martin Öberg

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/



#include <windows.h>
#include <newpluginapi.h>
#include <m_database.h>
#include "changeinfo.h"


static ListTypeDataItem countries[]={
	{0   ,"Unspecified"},
	{9999,"Other"},
	{93  ,"Afghanistan"},
	{355 ,"Albania"},
	{213 ,"Algeria"},
	{684 ,"American Samoa"},
	{376 ,"Andorra"},
	{244 ,"Angola"},
	{101 ,"Anguilla"},
	{102 ,"Antigua and Barbuda"},
	{5902,"Antilles"},
	{54  ,"Argentina"},
	{374 ,"Armenia"},
	{297 ,"Aruba"},
	{247 ,"Ascension Island"},
	{61  ,"Australia"},
	{43  ,"Austria"},
	{994 ,"Azerbaijan"},
	{103 ,"Bahamas"},
	{973 ,"Bahrain"},
	{880 ,"Bangladesh"},
	{104 ,"Barbados"},
	{120 ,"Barbuda"},
	{375 ,"Belarus"},
	{32  ,"Belgium"},
	{501 ,"Belize"},
	{229 ,"Benin"},
	{105 ,"Bermuda"},
	{975 ,"Bhutan"},
	{591 ,"Bolivia"},
	{387 ,"Bosnia and Herzegovina"},
	{267 ,"Botswana"},
	{55  ,"Brazil"},
	{106 ,"British Virgin Islands"},
	{673 ,"Brunei"},
	{359 ,"Bulgaria"},
	{226 ,"Burkina Faso"},
	{257 ,"Burundi"},
	{855 ,"Cambodia"},
	{237 ,"Cameroon"},
	{107 ,"Canada"},
	{178 ,"Canary Islands"},
	{238 ,"Cape Verde Islands"},
	{108 ,"Cayman Islands"},
	{236 ,"Central African Republic"},
	{235 ,"Chad"},
	{56  ,"Chile, Republic of"},
	{86  ,"China"},
	{672 ,"Christmas Island"},
	{6101,"Cocos-Keeling Islands"},
	{6102,"Cocos (Keeling) Islands"},
	{57  ,"Colombia"},
	{2691,"Comoros"},
	{243 ,"Congo, Democratic Republic of (Zaire)"},
	{242 ,"Congo, Republic of the"},
	{682 ,"Cook Islands"},
	{506 ,"Costa Rica"},
	{225 ,"Cote d'Ivoire (Ivory Coast)"},
	{385 ,"Croatia"},
	{53  ,"Cuba"},
	{357 ,"Cyprus"},
	{42  ,"Czech Republic"},
	{45  ,"Denmark"},
	{246 ,"Diego Garcia"},
	{253 ,"Djibouti"},
	{109 ,"Dominica"},
	{110 ,"Dominican Republic"},
	{593 ,"Ecuador"},
	{20  ,"Egypt"},
	{503 ,"El Salvador"},
	{240 ,"Equatorial Guinea"},
	{291 ,"Eritrea"},
	{372 ,"Estonia"},
	{251 ,"Ethiopia"},
	{298 ,"Faeroe Islands"},
	{500 ,"Falkland Islands"},
	{679 ,"Fiji"},
	{358 ,"Finland"},
	{33  ,"France"},
	{5901,"French Antilles"},
	{594 ,"French Guiana"},
	{689 ,"French Polynesia"},
	{241 ,"Gabon"},
	{220 ,"Gambia"},
	{995 ,"Georgia"},
	{49  ,"Germany"},
	{233 ,"Ghana"},
	{350 ,"Gibraltar"},
	{30  ,"Greece"},
	{299 ,"Greenland"},
	{111 ,"Grenada"},
	{590 ,"Guadeloupe"},
	{671 ,"Guam, US Territory of"},
	{502 ,"Guatemala"},
	{224 ,"Guinea"},
	{245 ,"Guinea-Bissau"},
	{592 ,"Guyana"},
	{509 ,"Haiti"},
	{504 ,"Honduras"},
	{852 ,"Hong Kong"},
	{36  ,"Hungary"},
	{354 ,"Iceland"},
	{91  ,"India"},
	{62  ,"Indonesia"},
	{98  ,"Iran (Islamic Republic of)"},
	{964 ,"Iraq"},
	{353 ,"Ireland"},
	{972 ,"Israel"},
	{39  ,"Italy"},
	{112 ,"Jamaica"},
	{81  ,"Japan"},
	{962 ,"Jordan"},
	{705 ,"Kazakhstan"},
	{254 ,"Kenya"},
	{686 ,"Kiribati"},
	{850 ,"Korea, North"},
	{82  ,"Korea, South"},
	{965 ,"Kuwait"},
	{706 ,"Kyrgyzstan"},
	{856 ,"Laos"},
	{371 ,"Latvia"},
	{961 ,"Lebanon"},
	{266 ,"Lesotho"},
	{231 ,"Liberia"},
	{218 ,"Libyan Arab Jamahiriya"},
	{4101,"Liechtenstein"},
	{370 ,"Lithuania"},
	{352 ,"Luxembourg"},
	{853 ,"Macau"},
	{389 ,"Macedonia (F.Y.R.O.M.)"},
	{261 ,"Madagascar"},
	{265 ,"Malawi"},
	{60  ,"Malaysia"},
	{960 ,"Maldives"},
	{223 ,"Mali"},
	{356 ,"Malta"},
	{692 ,"Marshall Islands"},
	{596 ,"Martinique"},
	{222 ,"Mauritania"},
	{230 ,"Mauritius"},
	{269 ,"Mayotte Island"},
	{52  ,"Mexico"},
	{691 ,"Micronesia, Federated States of"},
	{373 ,"Moldova, Republic of"},
	{377 ,"Monaco"},
	{976 ,"Mongolia"},
	{113 ,"Montserrat"},
	{212 ,"Morocco"},
	{258 ,"Mozambique"},
	{95  ,"Myanmar"},
	{264 ,"Namibia"},
	{674 ,"Nauru"},
	{977 ,"Nepal"},
	{31  ,"Netherlands"},
	{599 ,"Netherlands Antilles"},
	{114 ,"Nevis"},
	{687 ,"New Caledonia"},
	{64  ,"New Zealand"},
	{505 ,"Nicaragua"},
	{227 ,"Niger"},
	{234 ,"Nigeria"},
	{683 ,"Niue"},
	{6722,"Norfolk Island"},
	{47  ,"Norway"},
	{968 ,"Oman"},
	{92  ,"Pakistan"},
	{680 ,"Palau"},
	{507 ,"Panama"},
	{675 ,"Papua New Guinea"},
	{595 ,"Paraguay"},
	{51  ,"Peru"},
	{63  ,"Philippines"},
	{48  ,"Poland"},
	{351 ,"Portugal"},
	{121 ,"Puerto Rico"},
	{974 ,"Qatar"},
	{262 ,"Reunion Island"},
	{40  ,"Romania"},
	{6701,"Rota Island"},
	{7   ,"Russia"},
	{250 ,"Rwanda"},
	{290 ,"Saint Helena"},
	{115 ,"Saint Kitts"},
	{1141,"Saint Kitts and Nevis"},
	{122 ,"Saint Lucia"},
	{508 ,"Saint Pierre and Miquelon"},
	{116 ,"Saint Vincent and the Grenadines"},
	{670 ,"Saipan Island"},
	{378 ,"San Marino"},
	{239 ,"Sao Tome and Principe"},
	{966 ,"Saudi Arabia"},
	{442 ,"Scotland"},
	{221 ,"Senegal"},
	{248 ,"Seychelles"},
	{232 ,"Sierra Leone"},
	{65  ,"Singapore"},
	{4201,"Slovakia"},
	{386 ,"Slovenia"},
	{677 ,"Solomon Islands"},
	{252 ,"Somalia"},
	{27  ,"South Africa"},
	{34  ,"Spain"},
	{94  ,"Sri Lanka"},
	{249 ,"Sudan"},
	{597 ,"Suriname"},
	{268 ,"Swaziland"},
	{46  ,"Sweden"},
	{41  ,"Switzerland"},
	{963 ,"Syrian Arab Republic"},
	{886 ,"Taiwan"},
	{708 ,"Tajikistan"},
	{255 ,"Tanzania"},
	{66  ,"Thailand"},
	{6702,"Tinian Island"},
	{228 ,"Togo"},
	{690 ,"Tokelau"},
	{676 ,"Tonga"},
	{117 ,"Trinidad and Tobago"},
	{216 ,"Tunisia"},
	{90  ,"Turkey"},
	{709 ,"Turkmenistan"},
	{118 ,"Turks and Caicos Islands"},
	{688 ,"Tuvalu"},
	{256 ,"Uganda"},
	{380 ,"Ukraine"},
	{971 ,"United Arab Emirates"},
	{44  ,"United Kingdom"},
	{598 ,"Uruguay"},
	{1   ,"USA"},
	{711 ,"Uzbekistan"},
	{678 ,"Vanuatu"},
	{379 ,"Vatican City"},
	{58  ,"Venezuela"},
	{84  ,"Vietnam"},
	{123 ,"Virgin Islands (USA)"},
	{441 ,"Wales"},
	{681 ,"Wallis and Futuna Islands"},
	{685 ,"Western Samoa"},
	{967 ,"Yemen"},
	{381 ,"Yugoslavia"},
	{3811,"Yugoslavia - Serbia"},
	{382 ,"Yugoslavia - Montenegro"},
	{260 ,"Zambia"},
	{263 ,"Zimbabwe"},
};

static ListTypeDataItem timezones[]={
	{-100,"Unspecified"},
	{24  ,"GMT-12:00 Eniwetok; Kwajalein"},
	{23  ,"GMT-11:30"},
	{22  ,"GMT-11:00 Midway Island; Samoa"},
	{21  ,"GMT-10:30"},
	{20  ,"GMT-10:00 Hawaii"},
	{19  ,"GMT-9:30"},
	{18  ,"GMT-9:00 Alaska"},
	{17  ,"GMT-8:30"},
	{16  ,"GMT-8:00 Pacific Time; Tijuana"},
	{15  ,"GMT-7:30"},
	{14  ,"GMT-7:00 Arizona; Mountain Time"},
	{13  ,"GMT-6:30"},
	{12  ,"GMT-6:00 Central Time; Central America; Saskatchewan"},
	{11  ,"GMT-5:30"},
	{10  ,"GMT-5:00 Eastern Time; Bogota; Lima; Quito"},
	{9   ,"GMT-4:30"},
	{8   ,"GMT-4:00 Atlantic Time; Santiago; Caracas; La Paz"},
	{7   ,"GMT-3:30 Newfoundland"},
	{6   ,"GMT-3:00 Greenland; Buenos Aires; Georgetown"},
	{5   ,"GMT-2:30"},
	{4   ,"GMT-2:00 Mid-Atlantic"},
	{3   ,"GMT-1:30"},
	{2   ,"GMT-1:00 Cape Verde Islands; Azores"},
	{1   ,"GMT-0:30"},
	{0   ,"GMT+0:00 London; Dublin; Edinburgh; Lisbon; Casablanca"},
	{-1  ,"GMT+0:30"},
	{-2  ,"GMT+1:00 Central European Time; West Central Africa; Warsaw"},
	{-3  ,"GMT+1:30"},
	{-4  ,"GMT+2:00 Jerusalem; Helsinki; Harare; Cairo; Bucharest; Athens"},
	{-5  ,"GMT+2:30"},
	{-6  ,"GMT+3:00 Moscow; St. Petersburg; Nairobi; Kuwait; Baghdad"},
	{-7  ,"GMT+3:30 Tehran"},
	{-8  ,"GMT+4:00 Baku; Tbilisi; Yerevan; Abu Dhabi; Muscat"},
	{-9  ,"GMT+4:30 Kabul"},
	{-10 ,"GMT+5:00 Calcutta; Chennai; Mumbai; New Delhi; Ekaterinburg"},
	{-11 ,"GMT+5:30"},
	{-12 ,"GMT+6:00 Astana; Dhaka; Almaty; Novosibirsk; Sri Jayawardenepura"},
	{-13 ,"GMT+6:30 Rangoon"},
	{-14 ,"GMT+7:00 Bankok; Hanoi; Jakarta; Krasnoyarsk"},
	{-15 ,"GMT+7:30"},
	{-16 ,"GMT+8:00 Perth; Taipei; Singapore; Hong Kong; Beijing"},
	{-17 ,"GMT+8:30"},
	{-18 ,"GMT+9:00 Tokyo; Osaka; Seoul; Sapporo; Yakutsk"},
	{-19 ,"GMT+9:30 Darwin; Adelaide"},
	{-20 ,"GMT+10:00 East Australia; Guam; Vladivostok"},
	{-21 ,"GMT+10:30"},
	{-22 ,"GMT+11:00 Magadan; Solomon Is.; New Caledonia"},
	{-23 ,"GMT+11:30"},
	{-24 ,"GMT+12:00 Auckland; Wellington; Fiji; Kamchatka; Marshall Is."},
};

static ListTypeDataItem occupations[] = {
	{0, "Unspecified"},
	{1, "Academic"},
	{2, "Administrative"},
	{3, "Art/Entertainment"},
	{4, "College Student"},
	{5, "Computers"},
	{6, "Community & Social"},
	{7, "Education"},
	{8, "Engineering"},
	{9, "Financial Services"},
	{10, "Government"},
	{11, "High School Student"},
	{12, "Home"},
	{13, "ICQ - Providing Help"},
	{14, "Law"},
	{15, "Managerial"},
	{16, "Manufacturing"},
	{17, "Medical/Health"},
	{18, "Military"},
	{19, "Non-Government Organization"},
	{20, "Professional"},
	{21, "Retail"},
	{22, "Retired"},
	{23, "Science & Research"},
	{24, "Sports"},
	{25, "Technical"},
	{26, "University Student"},
	{27, "Web Building"},
	{99, "Other Services"}
};

static ListTypeDataItem genders[]={
	{0,"Unspecified"},
	{'M',"Male"},
	{'F',"Female"},
};

static ListTypeDataItem months[]={
	{0, "Unspecified"},
	{1, "January"},
	{2, "February"},
	{3, "March"},
	{4, "April"},
	{5, "May"},
	{6, "June"},
	{7, "July"},
	{8, "August"},
	{9, "September"},
	{10,"October"},
	{11,"November"},
	{12,"December"},
};

static ListTypeDataItem languages[]={
	{0, "None"},
	{55,"Afrikaans"},
	{58,"Albanian"},
	{1, "Arabic"},
	{59,"Armenian"},
	{68,"Azerbaijani"},
	{72,"Belorussian"},
	{2, "Bhojpuri"},
	{56,"Bosnian"},
	{3, "Bulgarian"},
	{4, "Burmese"},
	{5, "Cantonese"},
	{6, "Catalan"},
	{61,"Chamorro"},
	{7, "Chinese"},
	{8, "Croatian"},
	{9, "Czech"},
	{10,"Danish"},
	{11,"Dutch"},
	{12,"English"},
	{13,"Esperanto"},
	{14,"Estonian"},
	{15,"Farci"},
	{16,"Finnish"},
	{17,"French"},
	{18,"Gaelic"},
	{19,"German"},
	{20,"Greek"},
	{70,"Gujarati"},
	{21,"Hebrew"},
	{22,"Hindi"},
	{23,"Hungarian"},
	{24,"Icelandic"},
	{25,"Indonesian"},
	{26,"Italian"},
	{27,"Japanese"},
	{28,"Khmer"},
	{29,"Korean"},
	{69,"Kurdish"},
	{30,"Lao"},
	{31,"Latvian"},
	{32,"Lithuanian"},
	{65,"Macedonian"},
	{33,"Malay"},
	{63,"Mandarin"},
	{62,"Mongolian"},
	{34,"Norwegian"},
	{57,"Persian"},
	{35,"Polish"},
	{36,"Portuguese"},
	{60,"Punjabi"},
	{37,"Romanian"},
	{38,"Russian"},
	{39,"Serbo-Croatian"},
	{66,"Sindhi"},
	{40,"Slovak"},
	{41,"Slovenian"},
	{42,"Somali"},
	{43,"Spanish"},
	{44,"Swahili"},
	{45,"Swedish"},
	{46,"Tagalog"},
	{64,"Taiwaness"},
	{71,"Tamil"},
	{47,"Tatar"},
	{48,"Thai"},
	{49,"Turkish"},
	{50,"Ukrainian"},
	{51,"Urdu"},
	{52,"Vietnamese"},
	{67,"Welsh"},
	{53,"Yiddish"},
	{54,"Yoruba"},
};

const int ageRange[]={14,130};
const int yearRange[]={1880,2000};
const int dayRange[]={1,31};

SettingItem setting[]={
	//personal
	{"Personal",       LI_DIVIDER},
	{"Nickname",       LI_STRING,     DBVT_ASCIIZ, "Nick"},
	{"First name",     LI_STRING,     DBVT_ASCIIZ, "FirstName"},
	{"Last name",      LI_STRING,     DBVT_ASCIIZ, "LastName"},
	{"Age",            LI_NUMBER,     DBVT_WORD,   "Age",        (void*)ageRange},
	{"Gender",         LI_LIST,       DBVT_BYTE,   "Gender",     genders, sizeof(genders)/sizeof(genders[0])},
	{"About",          LI_LONGSTRING, DBVT_ASCIIZ, "About"},
	//password
	{"Password",       LI_DIVIDER},
	{"Password",       LI_STRING|LIF_PASSWORD,DBVT_ASCIIZ, "Password"},
	//contact
	{"Contact",        LI_DIVIDER},
	{"Primary e-mail", LI_STRING,     DBVT_ASCIIZ, "e-mail"},
	{"Homepage",       LI_STRING,     DBVT_ASCIIZ, "Homepage"},
	{"Street",         LI_STRING,     DBVT_ASCIIZ, "Street"},
	{"City",           LI_STRING,     DBVT_ASCIIZ, "City"},
	{"State",          LI_STRING,     DBVT_ASCIIZ, "State"},
	{"ZIP/postcode",   LI_STRING,     DBVT_ASCIIZ, "ZIP"},
	{"Country",        LI_LIST,       DBVT_WORD,   "Country",    countries, sizeof(countries)/sizeof(countries[0])},
	{"Phone number",   LI_STRING,     DBVT_ASCIIZ, "Phone"},
	{"Fax number",     LI_STRING,     DBVT_ASCIIZ, "Fax"},
	{"Cellular number",LI_STRING,     DBVT_ASCIIZ, "Cellular"},
	//more
	{"Personal Detail",LI_DIVIDER},
	{"Timezone",       LI_LIST|LIF_ZEROISVALID|LIF_SIGNED,DBVT_BYTE,   "Timezone", timezones, sizeof(timezones)/sizeof(timezones[0])},
	{"Year of birth",  LI_NUMBER,     DBVT_WORD,   "BirthYear",  (void*)yearRange},
	{"Month of birth", LI_LIST,       DBVT_BYTE,   "BirthMonth", months, sizeof(months)/sizeof(months[0])},
	{"Day of birth",   LI_NUMBER,     DBVT_BYTE,   "BirthDay",   (void*)dayRange},
	{"Spoken language 1", LI_LIST,    DBVT_ASCIIZ, "Language1",  languages, sizeof(languages)/sizeof(languages[0])},
	{"Spoken language 2", LI_LIST,    DBVT_ASCIIZ, "Language2",  languages, sizeof(languages)/sizeof(languages[0])},
	{"Spoken language 3", LI_LIST,    DBVT_ASCIIZ, "Language3",  languages, sizeof(languages)/sizeof(languages[0])},
	//work
	{"Work",           LI_DIVIDER},
	{"Company name",   LI_STRING,     DBVT_ASCIIZ, "Company"},
	{"Company homepage",LI_STRING,    DBVT_ASCIIZ, "CompanyHomepage"},
	{"Company street", LI_STRING,     DBVT_ASCIIZ, "CompanyStreet"},
	{"Company city",   LI_STRING,     DBVT_ASCIIZ, "CompanyCity"},
	{"Company state",  LI_STRING,     DBVT_ASCIIZ, "CompanyState"},
	{"Company phone",  LI_STRING,     DBVT_ASCIIZ, "CompanyPhone"},
	{"Company fax",    LI_STRING,     DBVT_ASCIIZ, "CompanyFax"},
	{"Company ZIP/postcode",LI_STRING,DBVT_ASCIIZ, "CompanyZIP"},
	{"Company country",LI_LIST,       DBVT_WORD,   "CompanyCountry",countries, sizeof(countries)/sizeof(countries[0])},
	{"Company department",LI_STRING,  DBVT_ASCIIZ, "CompanyDepartment"},
	{"Company position",LI_STRING,    DBVT_ASCIIZ, "CompanyPosition"},
	{"Company occupation",LI_LIST,    DBVT_WORD,   "CompanyOccupation", occupations, sizeof(occupations)/sizeof(occupations[0])}
};
const int settingCount=sizeof(setting)/sizeof(setting[0]);
