contacts.o: contacts.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
dbrw.o: dbrw.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
events.o: events.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
settings.o: settings.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
sql.o: sql.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
utf8.o: utf8.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
utils.o: utils.c dbrw.h ../../include/newpluginapi.h \
  ../../include/m_plugins.h ../../include/m_system.h \
  ../../include/m_database.h ../../include/m_utils.h \
  ../../include/m_langpack.h sqlite3/sqlite3.h contacts.h events.h \
  resource.h settings.h sql.h utf8.h utils.h
alter.o: sqlite3/alter.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
analyze.o: sqlite3/analyze.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
attach.o: sqlite3/attach.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
auth.o: sqlite3/auth.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
btree.o: sqlite3/btree.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
build.o: sqlite3/build.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
callback.o: sqlite3/callback.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
complete.o: sqlite3/complete.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
date.o: sqlite3/date.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
delete.o: sqlite3/delete.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
expr.o: sqlite3/expr.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
fts1.o: sqlite3/fts1.c sqlite3/fts1.h sqlite3/sqlite3.h \
  sqlite3/fts1_hash.h sqlite3/fts1_tokenizer.h sqlite3/sqlite3ext.h
fts1_hash.o: sqlite3/fts1_hash.c sqlite3/fts1_hash.h
fts1_porter.o: sqlite3/fts1_porter.c sqlite3/fts1_tokenizer.h \
  sqlite3/sqlite3.h
fts1_tokenizer1.o: sqlite3/fts1_tokenizer1.c sqlite3/fts1_tokenizer.h \
  sqlite3/sqlite3.h
func.o: sqlite3/func.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/vdbeInt.h sqlite3/os.h
hash.o: sqlite3/hash.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
insert.o: sqlite3/insert.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
legacy.o: sqlite3/legacy.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
loadext.o: sqlite3/loadext.c
main.o: sqlite3/main.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
opcodes.o: sqlite3/opcodes.c
os.o: sqlite3/os.c sqlite3/sqliteInt.h sqlite3/sqlite3.h sqlite3/hash.h \
  sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h sqlite3/btree.h \
  sqlite3/pager.h sqlite3/os.h
os_os2.o: sqlite3/os_os2.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
os_unix.o: sqlite3/os_unix.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
os_win.o: sqlite3/os_win.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h sqlite3/os_common.h
pager.o: sqlite3/pager.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
parse.o: sqlite3/parse.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
pragma.o: sqlite3/pragma.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
prepare.o: sqlite3/prepare.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
printf.o: sqlite3/printf.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
random.o: sqlite3/random.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
select.o: sqlite3/select.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
shell.o: sqlite3/shell.c sqlite3/sqlite3.h
table.o: sqlite3/table.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
tokenize.o: sqlite3/tokenize.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h sqlite3/keywordhash.h
trigger.o: sqlite3/trigger.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
update.o: sqlite3/update.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
utf.o: sqlite3/utf.c sqlite3/sqliteInt.h sqlite3/sqlite3.h sqlite3/hash.h \
  sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h sqlite3/btree.h \
  sqlite3/pager.h sqlite3/vdbeInt.h
util.o: sqlite3/util.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h
vacuum.o: sqlite3/vacuum.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/vdbeInt.h sqlite3/os.h
vdbe.o: sqlite3/vdbe.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h sqlite3/vdbeInt.h
vdbeapi.o: sqlite3/vdbeapi.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/vdbeInt.h sqlite3/os.h
vdbefifo.o: sqlite3/vdbefifo.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/vdbeInt.h
vdbemem.o: sqlite3/vdbemem.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h sqlite3/os.h sqlite3/vdbeInt.h
vtab.o: sqlite3/vtab.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
where.o: sqlite3/where.c sqlite3/sqliteInt.h sqlite3/sqlite3.h \
  sqlite3/hash.h sqlite3/parse.h sqlite3/vdbe.h sqlite3/opcodes.h \
  sqlite3/btree.h sqlite3/pager.h
